# Import blocks for migrating GitHub resources to the new module
# Generated by Azure GitHub Environment Bootstrap migration script
#
# INSTRUCTIONS:
# 1. Run 'terraform plan' to see what will be imported
# 2. Run 'terraform apply' to execute the imports
# 3. After successful import, you can delete this file
#
# NOTE: These import blocks assume the standard PagoPA naming conventions
# If your environments use different names, adjust the import IDs accordingly

# Import the main GitHub repository
import {
  to = module.github_repository.github_repository.this
  id = "dx"
}

# Import additional repository resources
import {
  to = module.github_repository.github_actions_repository_permissions.repo
  id = "dx"
}

import {
  to = module.github_repository.github_branch_default.main
  id = "dx"
}

# Import infra_cd environment for dev
import {
  to = module.github_repository.github_repository_environment.infra_cd["dev"]
  id = "dx:infra-dev-cd"
}

# Import app_cd environment for dev
import {
  to = module.github_repository.github_repository_environment.app_cd["dev"]
  id = "dx:app-dev-cd"
}

# Import opex_cd environment for dev
import {
  to = module.github_repository.github_repository_environment.opex_cd["dev"]
  id = "dx:opex-dev-cd"
}

# Import infra_ci environment for dev
import {
  to = module.github_repository.github_repository_environment.infra_ci["dev"]
  id = "dx:infra-dev-ci"
}

# Import opex_ci environment for dev
import {
  to = module.github_repository.github_repository_environment.opex_ci["dev"]
  id = "dx:opex-dev-ci"
}

# Import infra_cd environment for prod
import {
  to = module.github_repository.github_repository_environment.infra_cd["prod"]
  id = "dx:infra-prod-cd"
}

# Import app_cd environment for prod
import {
  to = module.github_repository.github_repository_environment.app_cd["prod"]
  id = "dx:app-prod-cd"
}

# Import opex_cd environment for prod
import {
  to = module.github_repository.github_repository_environment.opex_cd["prod"]
  id = "dx:opex-prod-cd"
}

# Import infra_ci environment for prod
import {
  to = module.github_repository.github_repository_environment.infra_ci["prod"]
  id = "dx:infra-prod-ci"
}

# Import opex_ci environment for prod
import {
  to = module.github_repository.github_repository_environment.opex_ci["prod"]
  id = "dx:opex-prod-ci"
}

