# GitHub repository module configuration
# Generated by Azure GitHub Environment Bootstrap migration script
module "github_repository" {
  source  = "pagopa-dx/github-environment-bootstrap/github"
  version = "~> 1.0"

  repository = {
    name                   = "dx"
    description            = "Devex repository for shared tools and pipelines."
    topics                 = ["developer-experience"]
    reviewers_teams        = ["engineering-team-devex"]
    pages_enabled          = true
    has_downloads          = true
    has_projects           = true
    has_issues             = true
    homepage_url           = "https://pagopa.github.io/dx/docs/"
    pull_request_bypassers = ["/dx-pagopa-bot"]
    environments           = ["dev", "prod"]
  }
}

resource "github_actions_secret" "codecov_token" {
  repository      = "dx"
  secret_name     = "CODECOV_TOKEN"
  plaintext_value = "REPLACE_ME"

  lifecycle {
    ignore_changes = [
      plaintext_value
    ]
  }
}
