# GitHub repository module configuration
# Generated by Azure GitHub Environment Bootstrap migration script
module "github_repository" {
  source  = "pagopa-dx/github-environment-bootstrap/github"
  version = "~> 1.0"

  repository = {
    name                   = "dx"
    description            = "Devex repository for shared tools and pipelines."
    topics                 = ["developer-experience"]
    reviewers_teams        = ["engineering-team-devex"]
    pages_enabled          = false
    has_downloads          = true
    has_projects           = true
    has_issues             = true
    app_cd_policy_tags     = ["@pagopa/dx-mcpserver@**"]
    homepage_url           = "https://dx.pagopa.it"
    pull_request_bypassers = ["/dx-pagopa-bot"]
    environments           = ["dev", "uat", "prod", "npm-prod-cd"]
    jira_boards_ids        = ["CES"]
  }
}
