name: "Slack Notification"
description: "Send a notification to a Slack channel"

inputs:
  id:
    description: "ID of the notification in mrkdwn format"
    required: true
  title:
    description: "Visible title of the notification in mrkdwn format"
    required: false
  text:
    description: "Text of the notification in mrkdwn format"
    required: false
  slack_webhook_url:
    description: "Slack Webhook URL to send the notification to"
    required: true

runs:
  using: "composite"

  steps:
    - name: Check inputs and set defaults
      id: check-values
      shell: bash
      env:
        INPUT_ID: ${{ inputs.id }}
        INPUT_TITLE: ${{ inputs.title }}
      run: |
        set -eu
        if [ "$INPUT_TITLE" == "" ]; then
          title="*$INPUT_ID*"
        else
          title="$INPUT_TITLE"
        fi

        echo "title=$title" >> "$GITHUB_OUTPUT"

    - name: Slack Notification
      uses: slackapi/slack-github-action@45a88b9581bfab2566dc881e2cd66d334e621e2c # v3.0.3
      with:
        webhook: ${{ inputs.slack_webhook_url }}
        webhook-type: incoming-webhook
        payload: |
          {
            "text": ${{ toJSON(inputs.id) }},
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ${{ toJSON(steps.check-values.outputs.title) }}
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ${{ toJSON(inputs.text) }}
                }
              }
            ]
          }
