name: "Slack Notification"
description: "Send a notification to a Slack channel"

inputs:
  id:
    description: "ID of the notification in mrkdwn format"
    required: true
  title:
    description: "Visible title of the notification in mrkdwn format"
    required: false
  text:
    description: "Text of the notification in mrkdwn format"
    required: false
  slack_webhook_url:
    description: "Slack Webhook URL to send the notification to"
    required: true

runs:
  using: "composite"

  steps:
    - name: Check inputs and set defaults
      id: check-values
      shell: bash
      env:
        INPUT_ID: ${{ inputs.id }}
        INPUT_TITLE: ${{ inputs.title }}
      run: |
        set -eu
        if [ "$INPUT_TITLE" == "" ]; then
          title="*$INPUT_ID*"
        else
          title="$INPUT_TITLE"
        fi

        echo "title=$title" >> "$GITHUB_OUTPUT"

    # Reference: https://github.com/slackapi/slack-github-action
    - name: Slack Notification
      uses: slackapi/slack-github-action@70cd7be8e40a46e8b0eced40b0de447bdb42f68e # v1.26.0
      env:
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        SLACK_WEBHOOK_URL: ${{ inputs.slack_webhook_url }}
        INPUT_ID: ${{ inputs.id }}
        INPUT_TEXT: ${{ inputs.text }}
        TITLE: ${{ steps.check-values.outputs.title }}
      with:
        payload: |
          {
            "text": "$INPUT_ID",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "$TITLE"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "$INPUT_TEXT"
                }
              }
            ]
          }
