name: "Convert Mermaid into SVG"
description: "Passed a .md file containing Mermaid diagrams, this action converts them into SVG format."

inputs:
  file_path:
    description: "Path to the .md file containing Mermaid diagrams."
    required: true

runs:
  using: "composite"

  steps:
    - name: Node Setup
      id: node-setup
      uses: pagopa/dx/.github/actions/node-setup@main
    
    - name: Install mermaid-cli
      shell: bash
      run: npm install -g @mermaid-js/mermaid-cli
    
    - name: Convert Mermaid to SVG
      shell: bash
      env:
        MD_FILE: ${{ inputs.file_path }}
      run: |
        # Convert .md to .svg
        echo "Converting $MD_FILE to SVG..."
        puppeteer_config="$(mktemp)"
        echo '{"args": ["--no-sandbox"]}' > "$puppeteer_config"
        
        # This command will convert the Mermaid diagrams in the .md file to SVG format
        # creating a new .svg file and overwriting the original .md file adding the image url.
        
        mmdc -i $MD_FILE -o $MD_FILE -t dark -b transparent -p "$puppeteer_config"
        echo "✅ Successfully converted into svg"
