import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

const { mockRunCommand } = vi.hoisted(() => ({
  mockRunCommand: vi.fn(),
}));

const { octokitMock } = vi.hoisted(() => ({
  octokitMock: {
    constructor: vi.fn(),
    instance: {
      paginate: vi.fn(),
      rest: {
        issues: {
          createComment: vi.fn(),
          deleteComment: vi.fn(),
          listComments: vi.fn(),
        },
      },
    },
  },
}));

vi.mock("../run-command.ts", () => ({
  runCommand: mockRunCommand,
}));

vi.mock("octokit", () => ({
  Octokit: vi.fn(
    class {
      paginate = octokitMock.instance.paginate;

      rest = octokitMock.instance.rest;

      constructor(options: unknown) {
        octokitMock.constructor(options);
      }
    },
  ),
}));

import { createDefaultTaskDispatcher } from "../default-dispatcher.ts";

describe("createDefaultTaskDispatcher", () => {
  let originalCwd = "";
  let tempDirectoryPath = "";

  beforeEach(() => {
    originalCwd = process.cwd();
    mockRunCommand.mockReset();
    octokitMock.constructor.mockReset();
    octokitMock.instance.rest.issues.createComment.mockReset();
    octokitMock.instance.rest.issues.deleteComment.mockReset();
    octokitMock.instance.rest.issues.listComments.mockReset();
    octokitMock.instance.paginate.mockReset();
    vi.stubEnv("CI", "false");
    vi.spyOn(console, "log").mockImplementation(() => undefined);
  });

  beforeEach(async () => {
    tempDirectoryPath = await fs.mkdtemp(
      path.join(os.tmpdir(), "dx-tasks-default-dispatcher-"),
    );
    process.chdir(tempDirectoryPath);
  });

  afterEach(async () => {
    process.chdir(originalCwd);
    await fs.rm(tempDirectoryPath, { force: true, recursive: true });
    vi.restoreAllMocks();
    vi.unstubAllEnvs();
  });

  it("registers terraformPlan and dispatches its decoded payload", async () => {
    mockRunCommand.mockResolvedValue({
      exitCode: 0,
      signal: null,
      stderr: "",
      stdout: "No changes.",
    });
    const dispatcher = createDefaultTaskDispatcher();

    await dispatcher.dispatchTask("terraformPlan", {
      modulePath: "/tmp/module",
      report: true,
    });

    expect(mockRunCommand).toHaveBeenCalledWith(
      "terraform",
      ["plan"],
      "/tmp/module",
      {
        TF_CLI_ARGS_plan: "-lock-timeout=120s ",
        TF_IN_AUTOMATION: "true",
      },
    );
    expect(console.log).toHaveBeenCalledExactlyOnceWith("No changes.");
    await expect(
      fs.readFile(
        path.join(
          tempDirectoryPath,
          ".dx-tasks",
          "terraform-plan",
          "L3RtcC9tb2R1bGU.json",
        ),
        "utf8",
      ),
    ).resolves.toBe(`{
  "modulePath": "/tmp/module",
  "notices": [],
  "planOutput": "No changes.",
  "success": true
}`);
  });

  it("registers prComment and returns the created comment metadata", async () => {
    octokitMock.instance.rest.issues.createComment.mockResolvedValue({
      data: {
        body: "New test comment",
        html_url: "https://github.com/pagopa/dx/issues/123#issuecomment-456",
        id: 456,
      },
    });
    const dispatcher = createDefaultTaskDispatcher();

    await expect(
      dispatcher.dispatchTask("prComment", {
        commentBody: "New test comment",
        footer: "_Generated by dx-tasks_",
        githubToken: "test-token",
        issueNumber: 123,
        owner: "pagopa",
        repo: "dx",
        title: "Build Results",
      }),
    ).resolves.toStrictEqual({
      commentId: 456,
      commentUrl: "https://github.com/pagopa/dx/issues/123#issuecomment-456",
    });
    expect(octokitMock.constructor).toHaveBeenCalledExactlyOnceWith({
      auth: "test-token",
    });
    expect(
      octokitMock.instance.rest.issues.createComment,
    ).toHaveBeenCalledExactlyOnceWith({
      body: "## Build Results\n\nNew test comment\n\n---\n\n_Generated by dx-tasks_",
      issue_number: 123,
      owner: "pagopa",
      repo: "dx",
    });
  });

  it("registers reportPrComment and posts the rendered report", async () => {
    await fs.mkdir(
      path.join(tempDirectoryPath, ".dx-tasks", "terraform-plan"),
      { recursive: true },
    );
    await fs.writeFile(
      path.join(
        tempDirectoryPath,
        ".dx-tasks",
        "terraform-plan",
        "example.json",
      ),
      JSON.stringify({
        modulePath: "./infra/modules/example",
        notices: [],
        planOutput: "No changes.",
      }),
      "utf8",
    );
    octokitMock.instance.rest.issues.createComment.mockResolvedValue({
      data: {
        body: "New test comment",
        html_url: "https://github.com/pagopa/dx/issues/123#issuecomment-456",
        id: 456,
      },
    });
    const dispatcher = createDefaultTaskDispatcher();

    await expect(
      dispatcher.dispatchTask("reportPrComment", {
        footer: "_Generated by dx-tasks_",
        githubToken: "test-token",
        issueNumber: 123,
        owner: "pagopa",
        repo: "dx",
      }),
    ).resolves.toStrictEqual({
      commentId: 456,
      commentUrl: "https://github.com/pagopa/dx/issues/123#issuecomment-456",
    });
    expect(
      octokitMock.instance.rest.issues.createComment,
    ).toHaveBeenCalledExactlyOnceWith({
     body: "### Terraform Plan: `./infra/modules/example` - ✅ Success\n\n> [!NOTE]\n> Full plan output is not included in this comment.\n> See the workflow run logs or downloaded Terraform plan report artifacts for the complete output.\n\n---\n\n_Generated by dx-tasks_",
      issue_number: 123,
      owner: "pagopa",
      repo: "dx",
    });
    expect(console.log).not.toHaveBeenCalled();
  });
});
