import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import * as z from "zod/mini";

import type {
  GitHubComment,
  GitHubCommentTarget,
  GitHubPrCommentClientFactory,
  PrCommentResult,
} from "../github/pr-comment.ts";

import { createTaskDispatcher } from "../dispatcher.ts";
import { reportPrComment } from "../report-pr-comment.ts";
import { ReportStore } from "../report-store.ts";
import { reportPrCommentTask } from "../tasks.ts";

const testReportSchema = z.object({
  message: z.string(),
});

const testReportNamespace = {
  name: "test-report",
  renderers: {
    markdown: (reports: readonly z.output<typeof testReportSchema>[]) =>
      reports.map(({ message }) => message).join("\n\n"),
  },
  schema: testReportSchema,
};

const createClient = ({
  comments = [],
  createdComment = {
    commentId: 456,
    commentUrl: "https://github.com/pagopa/dx/issues/123#issuecomment-456",
  },
}: {
  comments?: readonly GitHubComment[];
  createdComment?: PrCommentResult;
} = {}) => {
  const createComment = vi.fn<
    (target: GitHubCommentTarget, body: string) => Promise<PrCommentResult>
  >(async () => createdComment);
  const deleteComment = vi.fn<
    (owner: string, repo: string, commentId: number) => Promise<void>
  >(async () => undefined);
  const listComments = vi.fn<() => Promise<readonly GitHubComment[]>>(
    async () => comments,
  );
  const factory = vi.fn<GitHubPrCommentClientFactory>(() => ({
    createComment,
    deleteComment,
    listComments,
  }));

  return {
    createComment,
    deleteComment,
    factory,
    listComments,
  };
};

describe("reportPrComment task", () => {
  let tempDirectoryPath = "";

  const createReportStore = (): ReportStore =>
    new ReportStore(tempDirectoryPath).register(testReportNamespace);

  const seedReport = async (message: string): Promise<void> => {
    const namespaceDirectoryPath = path.join(
      tempDirectoryPath,
      ".dx-tasks",
      "test-report",
    );
    await fs.mkdir(namespaceDirectoryPath, { recursive: true });
    await fs.writeFile(
      path.join(namespaceDirectoryPath, "example.json"),
      JSON.stringify({ message }),
      "utf8",
    );
  };

  beforeEach(async () => {
    tempDirectoryPath = await fs.mkdtemp(
      path.join(os.tmpdir(), "dx-tasks-report-pr-comment-"),
    );
    vi.spyOn(console, "warn").mockImplementation(() => undefined);
  });

  afterEach(async () => {
    await fs.rm(tempDirectoryPath, { force: true, recursive: true });
    vi.restoreAllMocks();
  });

  it("posts the rendered report as a PR comment", async () => {
    await seedReport("### Report\n\nAll tasks completed.");
    const client = createClient();

    const result = await reportPrComment(
      {
        githubToken: "test-token",
        issueNumber: 123,
        owner: "pagopa",
        repo: "dx",
        searchPattern: "<!-- dx-report -->",
      },
      { reports: createReportStore() },
      client.factory,
    );

    expect(client.factory).toHaveBeenCalledExactlyOnceWith("test-token");
    expect(client.listComments).toHaveBeenCalledExactlyOnceWith({
      issueNumber: 123,
      owner: "pagopa",
      repo: "dx",
    });
    expect(client.createComment).toHaveBeenCalledExactlyOnceWith(
      {
        issueNumber: 123,
        owner: "pagopa",
        repo: "dx",
      },
      "### Report\n\nAll tasks completed.",
    );
    expect(result).toStrictEqual({
      commentId: 456,
      commentUrl: "https://github.com/pagopa/dx/issues/123#issuecomment-456",
    });
  });

  it("posts the rendered report with a title", async () => {
    await seedReport("### Report\n\nAll tasks completed.");
    const client = createClient();

    await reportPrComment(
      {
        githubToken: "test-token",
        issueNumber: 123,
        owner: "pagopa",
        repo: "dx",
        title: "Terraform Plan",
      },
      { reports: createReportStore() },
      client.factory,
    );

    expect(client.createComment).toHaveBeenCalledExactlyOnceWith(
      {
        issueNumber: 123,
        owner: "pagopa",
        repo: "dx",
      },
      "## Terraform Plan\n\n### Report\n\nAll tasks completed.",
    );
  });

  it("posts the rendered report with a footer", async () => {
    await seedReport("### Report\n\nAll tasks completed.");
    const client = createClient();

    await reportPrComment(
      {
        footer: "_Generated by dx-tasks_",
        githubToken: "test-token",
        issueNumber: 123,
        owner: "pagopa",
        repo: "dx",
      },
      { reports: createReportStore() },
      client.factory,
    );

    expect(client.createComment).toHaveBeenCalledExactlyOnceWith(
      {
        issueNumber: 123,
        owner: "pagopa",
        repo: "dx",
      },
      "### Report\n\nAll tasks completed.\n\n---\n\n_Generated by dx-tasks_",
    );
  });

  it("skips creating a PR comment when the rendered report is empty", async () => {
    const client = createClient();

    await expect(
      reportPrComment(
        {
          githubToken: "test-token",
          issueNumber: 123,
          owner: "pagopa",
          repo: "dx",
        },
        { reports: createReportStore() },
        client.factory,
      ),
    ).resolves.toBeUndefined();
    expect(client.factory).not.toHaveBeenCalled();
    expect(client.createComment).not.toHaveBeenCalled();
  });

  it("throws when the task context has no reports", async () => {
    const dispatcher = createTaskDispatcher();
    dispatcher.registerTask(reportPrCommentTask);

    await expect(
      dispatcher.dispatchTask("reportPrComment", {
        githubToken: "test-token",
        issueNumber: 123,
        owner: "pagopa",
        repo: "dx",
      }),
    ).rejects.toThrow("reportPrComment requires reports in the task context");
  });
});
