repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.94.1
    hooks:
      - id: terraform_tflint
        args:
          - --args=--disable-rule terraform_required_version
          - --args=--disable-rule terraform_required_providers
          - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
      - id: terraform_fmt
      - id: terraform_docs
        name: terraform_docs on modules
        args:
          - --hook-config=--create-file-if-not-exist=true
          - --args=--hide providers
        files: ^infra/modules/.*
      - id: terraform_docs
        name: terraform_docs on resources
        args:
          - --hook-config=--create-file-if-not-exist=true
        exclude: |
          (?x)^(
            infra/modules/.*?
          )$
      - id: terraform_validate
        args:
          - --args=-json
          - --args=-no-color
          - --hook-config=--retry-once-with-cleanup=true
      - id: terraform_trivy
        args:
          - --args=--skip-dirs="**/.terraform"
          - --args=--ignorefile=__GIT_WORKING_DIR__/.trivyignore
