repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.94.1
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
        name: terraform_docs on modules
        args:
          - --hook-config=--create-file-if-not-exist=true
          - --args=--hide providers
        exclude: |
          (?x)^(
            infra/repository/.*?|
            infra/identity/.*?|
            infra/resources/.*?
          )$
      - id: terraform_docs
        name: terraform_docs on resources
        args:
          - --hook-config=--create-file-if-not-exist=true
        exclude: |
          (?x)^(
            infra/modules/.*?
          )$
      - id: terraform_validate
        args:
          - --args=-json
          - --args=-no-color
          - --hook-config=--retry-once-with-cleanup=true
      - id: terraform_trivy
        args:
          - --args=--skip-dirs="**/.terraform"
          - --args=--ignorefile=__GIT_WORKING_DIR__/.trivyignore
