preferReuse: true

packageExtensions:
  eslint-plugin-perfectionist@*:
    dependencies:
      "@typescript-eslint/types": "*"
nodeLinker: node-modules

# To ensure that each workspace declares the dependencies it uses, disable
# hoisting. Packages won't be hoisted past the workspace that depends on them.
nmHoistingLimits: workspaces
