[tools]
acli = "latest"
aws-cli = { version = "latest", symlink_bins = "true" }
azure-cli = { version = "latest", uvx_args = "--prerelease=allow" }
copilot = "latest"
github-cli = "latest"
go = "1.26.4"
node = "24.14.1"
pre-commit = "latest"
ripgrep = "latest"
shellcheck = "latest"
terraform = "1.15.2"
terraform-docs = "latest"
tflint = "latest"
tfsec = "latest"

[env]
COREPACK_ENABLE_DOWNLOAD_PROMPT=0
NX_DAEMON=true
EDITOR="code --reuse-window --wait"

[tasks.setup-ide]
description = "Configue VS Code as the default editor for Git and other tools"
run = """
#!/usr/bin/env bash
git config --global --add safe.directory "$PWD"
"""
