packages:
  - packages/*
  - apps/*
  - infra/modules/*
  - infra/scripts
  - providers/*
  - containers/*
  - actions/*

catalog:
  prettier: 3.6.2
  eslint: ^9.30.1
  typescript: ~5.8.3
  tsup: ^8.5.0
  vitest: ^3.2.4
  '@vitest/coverage-v8': ^3.2.4
  '@tsconfig/node20': ^20.1.6
  '@types/node': ^20.19.4

catalogMode: strict

onlyBuiltDependencies:
  - esbuild

packageImportMethod: clone-or-copy
