packages:
  - packages/*
  - apps/*
  - infra/modules/*
  - infra/scripts
  - providers/*
  - containers/*
  - actions/*

catalog:
  '@tsconfig/node22': 22.0.2
  '@types/node': ^22.16.2
  prettier: 3.6.2
  tsup: 8.5.0
  typescript: ~5.8.3

cleanupUnusedCatalogs: true

onlyBuiltDependencies:
  - esbuild

pnpmfile: packages/pnpm-plugin-pagopa/pnpmfile.cjs
