packages:
  - packages/*
  - apps/*
  - infra/modules/*
  - infra/scripts
  - providers/*
  - containers/*
  - actions/*

catalog:
  '@tsconfig/node22': 22.0.2
  '@types/node': ^22.19.1
  '@types/semver': ^7.7.1
  '@vitest/coverage-v8': ^3.2.4
  eslint: ^9.39.1
  execa: ^9.6.0
  neverthrow: ^8.2.0
  plop: ^4.0.2
  prettier: 3.6.2
  semver: ^7.7.2
  tsup: ^8.5.0
  typescript: ~5.8.3
  vitest: ^3.2.4

onlyBuiltDependencies:
  - esbuild

pnpmfile: packages/pnpm-plugin-pagopa/pnpmfile.cjs
