packages:
  - packages/*
  - apps/*
  - infra/modules/*
  - infra/scripts
  - providers/*
  - containers/*
  - actions/*

catalog:
  '@tsconfig/node22': 22.0.2
  '@types/node': ^22.16.2
  '@types/semver': ^7.7.0
  plop: ^4.0.2
  prettier: 3.6.2
  semver: ^7.7.2
  tsup: ^8.5.0
  typescript: ~5.8.3

onlyBuiltDependencies:
  - esbuild

pnpmfile: packages/pnpm-plugin-pagopa/pnpmfile.cjs
