packages:
  - packages/*
  - apps/*
  - infra/modules/*
  - infra/scripts
  - providers/*
  - containers/*
  - actions/*

catalog:
  prettier: 3.6.2
  eslint: ^9.30.1
  typescript: ~5.8.3
  tsup: ^8.5.0
  vitest: ^3.2.4
  '@vitest/coverage-v8': ^3.2.4
  '@tsconfig/node22': 22.0.2
  '@types/node': ^22.16.2

linkWorkspacePackages: true

onlyBuiltDependencies:
  - esbuild

packageImportMethod: clone-or-copy

preferWorkspacePackages: true

saveWorkspaceProtocol: rolling
