name: "Get Modified Providers"
description: "Determines which Terraform providers have been modified compared to the default branch"

inputs:
  current_ref:
    description: "Current branch reference"
    required: false
    type: string
    default: ""

outputs:
  providers:
    description: "List of modified providers in the format [\"name1\", \"name2\"]"
    value: ${{ steps.get-providers.outputs.providers }}

runs:
  using: "composite"
  steps:
    - name: Get modified providers
      id: get-providers
      shell: bash
      run: |
        DEFAULT_BRANCH_SHA=$(git rev-parse origin/$(git remote show origin | awk '/HEAD branch/ {print $NF}'))
        echo "Default branch SHA: $DEFAULT_BRANCH_SHA"
        CURRENT_BRANCH_SHA=${{ inputs.current_ref || github.sha }}

        folders_list=$(git diff --name-only $DEFAULT_BRANCH_SHA $CURRENT_BRANCH_SHA apps/providers \
          | xargs -r dirname \
          | sed 's#^apps/providers/\([^/]*\).*#\1#' \
          | uniq \
          | jq -R -c . \
          | jq -s -c .)

        echo "Providers changed: $folders_list"
        echo "providers=$folders_list" >> $GITHUB_OUTPUT
