[tools]
github-cli = { version = "latest" }
pre-commit = "4.6"
terraform-docs = "0.24"
tflint = "0.63"
trivy = "0.74"

[env]
TFLINT_PLUGIN_DIR="{{config_root}}/.tflint.d/plugins"

[settings]
idiomatic_version_file_enable_tools = ["node", "terraform"]
minimum_release_age = "7d"
experimental = true
lockfile = true

[deps.tflint]
sources = [".tflint.hcl"]
outputs = [".tflint.d/plugins"]

[deps.pnpm]
