name: Get Files Diff
description: An action to get the list of modified files between the base branch and the current commit.

inputs:
  base_branch:
    description: The base branch
    type: string
    required: false
    default: main

outputs:
  modified_files:
    description: List of modified files
    value: ${{ steps.modified_files.outputs.files }}

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        fetch-depth: 0 # Recover all the commit history to be sure that main commit is here

    - name: Get modified files
      id: modified_files
      shell: bash
      run: |
        # Last base branch commit
        MAIN_COMMIT=$(git rev-parse origin/${{ inputs.base_branch }})

        # Last commit
        CURRENT_COMMIT=$(git rev-parse HEAD)

        # List of modified files
        MODIFIED_FILES=$(git diff --name-only $MAIN_COMMIT $CURRENT_COMMIT)

        # Print the list of modified files
        echo "$MODIFIED_FILES"

        # Set output
        echo 'files<<EOF' >> $GITHUB_OUTPUT
        echo '$MODIFIED_FILES' >> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT