name: Static Assets Deploy
description: Assets deployment to CDN or Front Door

# This action allows you to deploy the passed asset to Azure CDN Classic or Azure Front Door.
# The asset must be the directory that contains all the files you want to sync.

inputs:
  use_cdn_classic:
    description: Set to true to use Azure CDN Classic instead of Front Door (default is Front Door).
    required: false
    default: "false"
  storage_account_name:
    description: Azure Storage account name where the assets will be uploaded.
    required: true
  blob_container_name:
    description: Blob container name within the Azure Storage account.
    required: true
  resource_group_name:
    description: Resource group name.
    required: true
  profile_name:
    description: Profile name associated with the endpoint.
    required: true
  endpoint_name:
    description: Endpoint name where the assets will be served.
    required: true
  selective_purge_paths:
    description: |
      List of relative paths for files to include in the purge. Leave empty to purge all files.
      Paths should be relative to the synchronized directory (sync_dir_name).
      For example, if syncing ./dist, to include ./dist/path/file1 and ./dist/path/file2, specify "./path/file1 ./path/file2."
      To recursively purge an entire directory, use the pattern "./path/dir/*".

      For CDN Classic, the format should follow the parameters as described in the official documentation:
      https://learn.microsoft.com/en-us/cli/azure/cdn/endpoint?view=azure-cli-latest#az-cdn-endpoint-purge-required-parameters

      For Front Door, the format should follow the parameters as described in the official documentation:
      https://learn.microsoft.com/en-us/cli/azure/afd/endpoint?view=azure-cli-latest#az-afd-endpoint-purge-required-parameters
    required: false
  sync_dir_name:
    description: Path to the files directory (Default is 'dist')
    required: false
    default: "dist"
  working_directory:
    description: The path of the directory containing the folder to be synchronized (Default is '.')
    required: false
    default: "."


runs:
  using: composite
  steps:
    ## Sync Storage
    # Files from working_directory/sync_dir_name will be synced to the storage account (Default is './dist')
    - name: Sync Storage
      shell: bash
      run: |
        az storage blob sync \
          --container ${{ inputs.blob_container_name }} \
          --account-name ${{ inputs.storage_account_name }} \
          --source "${{ env.FOLDER_NAME }}"
      working-directory: ${{ env.WORKING_DIRECTORY }}
      env:
        FOLDER_NAME: ${{ inputs.sync_dir_name || 'dist' }}
        WORKING_DIRECTORY: ${{ inputs.working_directory || '.' }}

    ## Purge - Selective paths (CDN Classic)
    - name: Purge selected files
      if: ${{ inputs.use_cdn_classic == 'true' && inputs.selective_purge_paths != '' }}
      shell: bash
      run: |
        az cdn endpoint purge \
          --resource-group ${{ inputs.resource_group_name }} \
          --endpoint-name ${{ inputs.endpoint_name }} \
          --profile-name ${{ inputs.profile_name }} \
          --content-paths $(echo "${{ inputs.selective_purge_paths }}" | sed -e "s/\([^ ]*\)/'\1'/g")

    ## Purge - All files (CDN Classic)
    - name: Purge all files
      if: ${{ inputs.use_cdn_classic == 'true' && inputs.selective_purge_paths == '' }}
      shell: bash
      run: |
        az cdn endpoint purge \
          --resource-group ${{ inputs.resource_group_name }} \
          --endpoint-name ${{ inputs.endpoint_name }} \
          --profile-name ${{ inputs.profile_name }} \
          --content-paths "/*"

    ## Purge - Selective paths (Front Door)
    - name: Purge selected files
      if: ${{ inputs.use_cdn_classic != 'true' && inputs.selective_purge_paths != '' }}
      shell: bash
      run: |
        az afd endpoint purge \
          --resource-group ${{ inputs.resource_group_name }} \
          --endpoint-name ${{ inputs.endpoint_name }} \
          --profile-name ${{ inputs.profile_name }} \
          --content-paths $(echo "${{ inputs.selective_purge_paths }}" | sed -e "s/\([^ ]*\)/'\1'/g")

    ## Purge - All files (Front Door)
    - name: Purge all files
      if: ${{ inputs.use_cdn_classic != 'true' && inputs.selective_purge_paths == '' }}
      shell: bash
      run: |
        az afd endpoint purge \
          --resource-group ${{ inputs.resource_group_name }} \
          --endpoint-name ${{ inputs.endpoint_name }} \
          --profile-name ${{ inputs.profile_name }} \
          --content-paths "/*"
