name: "Log Telemetry Event"
description: "Append a telemetry event to the session file"

inputs:
  name:
    description: "Event name"
    required: true

  body:
    description: "(Optional) Event body/message plain text"
    required: false
    default: ""

  is_exception:
    description: "If 'true', logs this event as an exception instead of a custom event"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Append event
      shell: bash
      env:
        INPUT_NAME: ${{inputs.name }}
        INPUT_BODY: ${{inputs.body}}
        INPUT_IS_EXCEPTION: ${{inputs.is_exception}}
      run: |
        if [ -z "$OTEL_EVENT_FILE" ]; then
          echo "OTEL_EVENT_FILE not set" >&2; exit 1;
        fi

        echo "is exception: $INPUT_IS_EXCEPTION"

        if [ "$INPUT_IS_EXCEPTION" = "true" ] || [ "$INPUT_IS_EXCEPTION" = "true" ]; then
          EXC=true
        else
          EXC=false
        fi

        echo "{\"name\":\"$INPUT_NAME\",\"body\":\"$INPUT_BODY\",\"exception\":$EXC}" >> "$OTEL_EVENT_FILE"

        cat "$OTEL_EVENT_FILE"
