#!/usr/bin/env bash
set -euo pipefail

# Create a pull request with generated dashboard changes
# Inputs:
#   PR_TITLE - Title for the pull request
#   PR_BODY - Description for the pull request
#   BASE_BRANCH - Base branch for the PR
#   CHANGED_DASHBOARDS - JSON array of changed dashboard paths
#   RUN_ID - GitHub run ID for unique branch naming
# Outputs:
#   Sets GITHUB_OUTPUT: pull-request-number, pull-request-url

BRANCH_NAME="chores/update-opex-dashboards-${RUN_ID}"

# Configure git
git config user.name "github-actions[bot]"
git config user.email "github-actions[bot]@users.noreply.github.com"

# Create and push branch
git checkout -b "${BRANCH_NAME}"
git add .
git commit -m "${PR_TITLE}"
git push origin "${BRANCH_NAME}"

# Create PR body with changed dashboards using printf for safe substitution
PR_BODY_FILE=$(mktemp)
{
  printf '%s\n\n' "${PR_BODY}"
  printf '### Changed Dashboards\n```json\n'
  printf '%s\n' "${CHANGED_DASHBOARDS}"
  printf '```\n\n---\n'
  printf '*This PR was automatically generated by the OpEx Dashboard action.*\n'
} > "${PR_BODY_FILE}"

# Create pull request
PR_URL=$(gh pr create \
  --base "${BASE_BRANCH}" \
  --head "${BRANCH_NAME}" \
  --title "${PR_TITLE}" \
  --body-file "${PR_BODY_FILE}")

PR_NUMBER=$(echo "${PR_URL}" | grep -oE '[0-9]+$')
echo "pull-request-number=${PR_NUMBER}" >> "${GITHUB_OUTPUT}"
echo "pull-request-url=${PR_URL}" >> "${GITHUB_OUTPUT}"

rm -f "${PR_BODY_FILE}"

echo "Created PR #${PR_NUMBER}: ${PR_URL}"
