#!/usr/bin/env python3
"""Single-call LLM judge for skill-eval tasks (generated by harbor-mod).

Reads the eval rubric (prompt + expected_output + expectations), the Copilot
CLI transcript, and the recursive workspace packet; calls the GitHub Copilot
responses endpoint through LiteLLM once and writes ``{reward: 0..1, reason}``.

Env expected (set via task.toml [verifier.env]):
  OPENAI_API_BASE=https://api.githubcopilot.com
  OPENAI_API_KEY=${COPILOT_GITHUB_TOKEN}
  LITELLM_DROP_PARAMS=true
  LITELLM_ROUTE_ALL_CHAT_OPENAI_TO_RESPONSES=true
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path


def _read(path: str, limit: int = 60_000) -> str:
    p = Path(path)
    if not p.is_file():
        return ""
    text = p.read_text(errors="replace")
    return text[:limit] + ("\n...[truncated]" if len(text) > limit else "")


def _parse_reward(payload: str) -> dict:
    """Parse the judge LLM response, tolerating code fences / prose around JSON."""
    start = payload.find("{")
    end = payload.rfind("}")
    if start == -1 or end == -1 or end <= start:
        raise ValueError(f"no JSON object in judge response: {payload[:200]!r}")
    data = json.loads(payload[start : end + 1])
    reward = float(data["reward"])
    reward = max(0.0, min(1.0, reward))
    return {"reward": reward, "reason": str(data.get("reason", ""))}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--rubric", required=True)
    parser.add_argument("--transcript", required=True)
    parser.add_argument("--packet", required=True)
    parser.add_argument("--output", required=True)
    parser.add_argument("--reason-output", required=True)
    args = parser.parse_args()

    rubric = json.loads(Path(args.rubric).read_text())
    judge_model = rubric.get("judge_model", "openai/gpt-5.6-luna")
    expectations = rubric.get("expectations", [])
    expected_output = rubric.get("expected_output", "")
    prompt_text = rubric.get("prompt", "")

    transcript = _read(args.transcript)
    packet = _read(args.packet, limit=40_000)

    user = (
        "You are a strict grader for an AI coding-agent evaluation.\n"
        "Evaluate the transcript against the expected output and the "
        "expectations below. Score the overall result 0.0 (completely failed) "
        "to 1.0 (fully met). Be fair: partial credit is allowed.\n\n"
        f"## Agent task prompt\n{prompt_text}\n\n"
        f"## Expected output\n{expected_output}\n\n"
        f"## Expectations\n"
        + "\n".join(f"{i+1}. {e}" for i, e in enumerate(expectations))
        + "\n\n"
        f"## Transcript\n{transcript}\n\n"
        f"## Workspace packet (files produced)\n{packet}\n\n"
        "Respond with ONLY a JSON object: "
        '{"reward": <float 0..1>, "reason": "<short justification>"}'
    )

    try:
        from litellm import completion
    except ImportError as exc:  # pragma: no cover
        print(f"litellm not available: {exc}", file=sys.stderr)
        return 1

    response = completion(
        model=judge_model,
        messages=[{"role": "user", "content": user}],
        temperature=0.2,
    )
    payload = response.choices[0].message.content
    result = _parse_reward(payload)

    Path(args.output).parent.mkdir(parents=True, exist_ok=True)
    Path(args.output).write_text(json.dumps(result))
    Path(args.reason_output).write_text(result["reason"])
    print(f"reward={result['reward']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
