#!/bin/bash
# Reference solution stub (generated by harbor-mod).
# These eval tasks are agent-behaviour evaluations (not oracle-solvable in a
# deterministic way); the oracle run is used only to validate that the task
# builds and the verifier produces a reward.
exit 0
