#!/bin/bash
# Verifier for a skill-eval task (generated by harbor-mod).
#
# Runs in a SEPARATE verifier container that never sees the agent's injected
# skills, workspace, or agent logs. Harbor transfers only the task-level
# `artifacts` (here: /workspace + /logs/agent/copilot-cli.txt) re-materialized
# at their original paths, plus /logs/artifacts/; /logs/verifier/ is mounted
# for the reward.
set -uo pipefail

# --- F1: skill load + invoke proof (agent trajectory under /logs/agent) ----------
# Enforced unless SKILL_EVAL_ENFORCE_SKILL_USE=false (e.g. without-skill jobs).
SKILL_OK=1
TRANSCRIPT=""
if [ -d /logs/agent ]; then
  TRANSCRIPT=$(find /logs/agent -type f -name '*.jsonl' 2>/dev/null | head -n 1)
fi
if [ "${SKILL_EVAL_ENFORCE_SKILL_USE:-true}" = "true" ]; then
  SKILL_NAME="${SKILL_EVAL_SKILL_NAME:-{{SKILL_NAME}}}"
  if [ -n "$TRANSCRIPT" ]; then
    # load: skill context injected into the user turn
    if ! grep -q '<skill-context' "$TRANSCRIPT" 2>/dev/null; then
      SKILL_OK=0
    fi
    # invoke: at least one tool call to the `skill` tool
    if ! grep -q '"name" *: *"skill"' "$TRANSCRIPT" 2>/dev/null; then
      SKILL_OK=0
    fi
  else
    SKILL_OK=0
  fi
fi

if [ "$SKILL_OK" -eq 0 ]; then
  echo 0 > /logs/verifier/reward.txt
  echo "skill_use_ok=$SKILL_OK" > /logs/verifier/reason.txt
  exit 0
fi

# --- LLM judge (single call via judge.py) -------------------------------------
JUDGE_TOKEN="${OPENAI_API_KEY:-${COPILOT_GITHUB_TOKEN:-${GH_TOKEN:-${GITHUB_TOKEN:-}}}}"
if [ -n "$JUDGE_TOKEN" ]; then
  export PATH="$HOME/.local/bin:$PATH"
  # uv is baked into the verifier image (verifier-Dockerfile); keep a fallback
  # install so the same test.sh also works in shared-verifier mode.
  if ! command -v uv >/dev/null 2>&1; then
    curl -LsSf https://astral.sh/uv/install.sh | sh
    export PATH="$HOME/.local/bin:$PATH"
  fi
  # Recursive workspace packet: judge.py reads the produced files (transferred
  # artifact /workspace) plus the Copilot CLI transcript (/logs/agent).
  mkdir -p /logs/artifacts
  {
    for f in $(find /workspace -type f -not -path '*/.agents/*' -not -path '*/.git/*' | sort); do
      printf '
--- %s ---

' "$f"
      cat "$f"
    done
  } > /logs/artifacts/workspace-packet.md 2>/dev/null || true

  uv run --no-project --with litellm python /tests/judge.py \
    --rubric /tests/rubric.json \
    --transcript "$TRANSCRIPT" \
    --packet /logs/artifacts/workspace-packet.md \
    --output /logs/verifier/reward.json \
    --reason-output /logs/verifier/reason.txt \
    || true

  if [ -f /logs/verifier/reward.json ]; then
    python3 -c 'import json,sys; d=json.load(open("/logs/verifier/reward.json")); print(d["reward"])' \
      > /logs/verifier/reward.txt 2>/dev/null \
      || echo 0 > /logs/verifier/reward.txt
  else
    echo 0 > /logs/verifier/reward.txt
  fi
else
  echo 1 > /logs/verifier/reward.txt
fi
