name: "Swap App Service Slot"
description: "Incrementally shift traffic to staging slot, run canary script, shift traffic and finalize with slot swap."

inputs:
  resource_group_name:
    description: "Azure Resource Group name"
    required: true
  resource_name:
    description: "Azure Web App name"
    required: true
  resource_type:
    description: "Type of Azure resource (e.g., 'appsvc' or 'containerapp')"
    required: true

runs:
  using: "composite"

  steps:
    - name: Check out canary-monitor script
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        sparse-checkout: |
          canary-monitor.sh
        sparse-checkout-cone-mode: false

    - name: Set GitHub Path
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH

    - name: Incremental Rollout to Staging Slot
      shell: bash
      env:
        RESOURCE_GROUP_NAME: ${{ inputs.resource_group_name }}
        RESOURCE_NAME: ${{ inputs.resource_name }}
        RESOURCE_TYPE: ${{ inputs.resource_type }}
      run: rollout.sh "$RESOURCE_GROUP_NAME" "$RESOURCE_NAME" "$RESOURCE_TYPE"
