name: "Make artifact"
description: "Make an artifact from build outputs"

inputs:
  package-manager:
    description: "The package manager used in the workspace (yarn, pnpm)"
    required: true
  workspace-name:
    description: "The name of the workspace to build the artifact from"
    required: true
  workspace-path:
    description: "The path to the workspace to build the artifact from"
    required: true

outputs:
  artifact-path:
    description: "The path to the created artifact"
    value: ${{ steps.make-artifact.outputs.artifact-path }}

runs:
  using: "composite"

  steps:
    - name: Make artifact
      id: make-artifact
      shell: bash
      env:
        PACKAGE_MANAGER: ${{ inputs.package-manager }}
        WORKSPACE_NAME: ${{ inputs.workspace-name }}
        WORKSPACE_PATH: ${{ inputs.workspace-path }}
        BUNDLE_NAME: ${{ inputs.workspace-name }}
      working-directory: ${{ inputs.workspace-path }}
      run: |
        if grep -rq --include='next.config.*' 'standalone' .; then
          echo "::debug::The workspace contains a Next.js standalone app"
          mv .next/static .next/standalone/"$WORKSPACE_PATH"/.next
          if [ -d public ]; then
            mv public .next/standalone/"$WORKSPACE_PATH"
          fi
          # on pnpm, use top-level node_modules
          if [ "$PACKAGE_MANAGER" = "pnpm" ]; then
            if [ -d .next/standalone/"$WORKSPACE_PATH"/node_modules ]; then
              rm -rf .next/standalone/"$WORKSPACE_PATH"/node_modules
            fi
            mv .next/standalone/node_modules .next/standalone/"$WORKSPACE_PATH"
          fi
          cd .next/standalone/"$WORKSPACE_PATH"
          zip -r -q "$BUNDLE_NAME".zip .
          echo "artifact-path=$(realpath "$BUNDLE_NAME.zip")" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        if [ "$PACKAGE_MANAGER" = "pnpm" ]; then
          echo "::debug::The workspace uses pnpm"
          # we use --legacy to avoid hardlinking workspace packages
          # https://github.com/orgs/pnpm/discussions/9015
          pnpm --filter $WORKSPACE_NAME deploy --legacy --prod bundle
          cd bundle && zip -yr $BUNDLE_NAME.zip .
          echo "artifact-path=$(realpath $BUNDLE_NAME.zip)" >> $GITHUB_OUTPUT
          exit 0
        fi

        if [ "$PACKAGE_MANAGER" = "yarn" ]; then
          echo "::debug::The workspace uses yarn"
          yarn workspaces focus --production
          zip -r $BUNDLE_NAME.zip .
          echo "artifact-path=$(realpath $BUNDLE_NAME.zip)" >> $GITHUB_OUTPUT
          exit 0
        fi

        echo "::error::Unsupported package manager: $PACKAGE_MANAGER"
        exit 1
