#!/usr/bin/env python3
"""Validate the CSR generated by the deterministic renew TLS certificate test."""

import argparse

from cryptography import x509
from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography.x509.oid import ExtensionOID, NameOID


def validate_csr(csr_path, expected_domain):
    with open(csr_path, "rb") as csr_file:
        csr = x509.load_der_x509_csr(csr_file.read())

    common_name = csr.subject.get_attributes_for_oid(NameOID.COMMON_NAME)[0].value
    subject_alternative_names = csr.extensions.get_extension_for_oid(
        ExtensionOID.SUBJECT_ALTERNATIVE_NAME
    ).value.get_values_for_type(x509.DNSName)
    public_key = csr.public_key()

    assert common_name == expected_domain
    assert subject_alternative_names == [expected_domain]
    assert isinstance(public_key, rsa.RSAPublicKey)
    assert public_key.key_size == 2048


def main(argv=None):
    parser = argparse.ArgumentParser()
    parser.add_argument("csr_path")
    parser.add_argument("expected_domain")
    args = parser.parse_args(argv)

    validate_csr(args.csr_path, args.expected_domain)


if __name__ == "__main__":
    main()
