name: Code Build 
description: An action to build the artifact

inputs:
  workspace_name:
    description: The name of the workspace to create the artifact for.
    type: string
    required: true
  bundle_name:
    description: Name of the bundle
    type: string
    required: false
  base_workdir:
    description: The base workdir (Default is ./out)
    type: string
    required: false

runs:
  using: composite
  steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      name: Checkout

    - name: Prune
      shell: bash
      run: npx turbo@1.13.3 prune --scope ${{ inputs.workspace_name }}

    - name: Setup yarn
      shell: bash
      run: corepack enable

    - name: Setup Node.js
      uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
      with:
        node-version-file: ".node-version"
        cache: "yarn"
        cache-dependency-path: "${{ inputs.base_workdir || './out' }}/yarn.lock"

    - name: Install dependencies
      shell: bash
      run: yarn install --immutable
      working-directory: ${{ inputs.base_workdir || './out' }}
    
    - name: Build
      shell: bash
      run: yarn build
      working-directory: ${{ inputs.base_workdir || './out' }}

    - name: Upload Artifact
      uses: actions/upload-artifact@694cdabd8bdb0f10b2cea11669e1bf5453eed0a6 # v4.2.0
      with:
        name: ${{ inputs.bundle_name || 'bundle' }}
        path: "${{ inputs.base_workdir || './out' }}"
        if-no-files-found: error
        retention-days: 7