name: "Build Workspace"
description: "Builds a workspace in a monorepo and handles dependencies."

inputs:
  workspace_name:
    description: "The name of the workspace to build."
    required: true

outputs:
  package-manager:
    description: "The package manager used in the monorepo (npm, yarn, or pnpm)."
    value: ${{ steps.node-setup.outputs.package-manager }}
  workspace-path:
    description: "The path to the built workspace."
    value: ${{ steps.get-workspace-path.outputs.workspace-path }}

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      id: node-setup
      uses: pagopa/dx/.github/actions/node-setup@main

    - name: Detect build tool
      id: detect-build-tool
      shell: bash
      run: |
        if [ -f "nx.json" ]; then
          echo "build-tool=nx" >> $GITHUB_OUTPUT
        else
          echo "build-tool=turbo" >> $GITHUB_OUTPUT
        fi

    - name: Get Workspace path
      id: get-workspace-path
      shell: bash
      run: |
        $run_command="$PACKAGE_MANAGER dlx"
        if [ "$BUILD_TOOL" == "turbo" ]; then
          $workspace_list=$($run_command turbo ls --output=json)
          WORKSPACE_PATH=$(echo "$workspace_list" | jq -sr --arg NAME "$WORKSPACE_NAME" '.[].packages.items[] | select(.name == $NAME).path')
        else
          $workspace_detail=$($run_command nx show project "$WORKSPACE_NAME" --json)
          echo "::group::Workspace Detail"
          echo "$workspace_detail"
          echo "::endgroup::"
          WORKSPACE_PATH=$(echo "$workspace_detail" | jq -r .root)
        fi
        echo "workspace-path=$WORKSPACE_PATH" >> $GITHUB_OUTPUT
      env:
        WORKSPACE_NAME: ${{ inputs.workspace_name }}
        PACKAGE_MANAGER: ${{ steps.node-setup.outputs.package-manager }}
        BUILD_TOOL: ${{ steps.detect-build-tool.outputs.build-tool }}

    # If certain conditions are met, use flat node_modules structure
    - name: Enable compatibility mode
      id: compatibility-mode
      shell: bash
      run: |
        if [ "$PACKAGE_MANAGER" = "yarn" ]; then
          echo "enabled=true" >> $GITHUB_OUTPUT
        elif grep -rq --include='next.config.*' 'standalone' "$WORKSPACE_PATH"; then
          echo "enabled=true" >> $GITHUB_OUTPUT
        else
          echo "enabled=false" >> $GITHUB_OUTPUT
        fi
      env:
        WORKSPACE_PATH: ${{ steps.get-workspace-path.outputs.workspace-path }}
        PACKAGE_MANAGER: ${{ steps.node-setup.outputs.package-manager }}

    - name: Install dependencies (pnpm)
      if: ${{ steps.node-setup.outputs.package-manager == 'pnpm' }}
      shell: bash
      run: |
        if [ "$COMPABILITY_MODE" = "true" ]; then
          pnpm config set --location=project nodeLinker hoisted
          rm -rf node_modules
          pnpm -r exec rm -rf node_modules
        fi
        pnpm --filter "$WORKSPACE_NAME..." install
      env:
        COMPABILITY_MODE: ${{ steps.compatibility-mode.outputs.enabled }}
        WORKSPACE_NAME: ${{ inputs.workspace_name }}

    - name: Install dependencies (yarn)
      if: ${{ steps.node-setup.outputs.package-manager == 'yarn' }}
      shell: bash
      run: |
        if [ "$COMPABILITY_MODE" = "true" ]; then
          yarn config set nodeLinker node-modules
          yarn config set nmHoistingLimits workspaces
        fi
        yarn install --immutable
      env:
        COMPABILITY_MODE: ${{ steps.compatibility-mode.outputs.enabled }}

    - name: Install dependencies (npm)
      if: ${{ steps.node-setup.outputs.package-manager == 'npm' }}
      shell: bash
      run: npm ci

    - name: Build (turbo)
      if: ${{ steps.detect-build-tool.outputs.build-tool == 'turbo' }}
      shell: bash
      run: npx turbo build --filter $WORKSPACE_NAME
      env:
        WORKSPACE_NAME: ${{ inputs.workspace_name }}

    - name: Build (nx)
      if: ${{ steps.detect-build-tool.outputs.build-tool == 'nx' }}
      shell: bash
      run: npx nx run $WORKSPACE_NAME:build
      env:
        WORKSPACE_NAME: ${{ inputs.workspace_name }}
