import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

import type {
  GitHubComment,
  GitHubCommentTarget,
  GitHubPrCommentClientFactory,
  PrCommentResult,
} from "../pr-comment.ts";

import { payloadSchema, prComment } from "../pr-comment.ts";

const createClient = ({
  comments = [],
  createdComment = {
    commentId: 456,
    commentUrl: "https://github.com/pagopa/dx/issues/123#issuecomment-456",
  },
  deleteComment = vi.fn<
    (owner: string, repo: string, commentId: number) => Promise<void>
  >(async () => undefined),
  listComments = vi.fn<() => Promise<readonly GitHubComment[]>>(
    async () => comments,
  ),
}: {
  comments?: readonly GitHubComment[];
  createdComment?: PrCommentResult;
  deleteComment?: (
    owner: string,
    repo: string,
    commentId: number,
  ) => Promise<void>;
  listComments?: () => Promise<readonly GitHubComment[]>;
} = {}) => {
  const createComment = vi.fn<
    (target: GitHubCommentTarget, body: string) => Promise<PrCommentResult>
  >(async () => createdComment);
  const factory = vi.fn<GitHubPrCommentClientFactory>(() => ({
    createComment,
    deleteComment,
    listComments,
  }));

  return {
    createComment,
    deleteComment,
    factory,
    listComments,
  };
};

const payload = {
  commentBody: "New test comment",
  githubToken: "test-token",
  issueNumber: 123,
  owner: "pagopa",
  repo: "dx",
};

beforeEach(() => {
  vi.spyOn(console, "warn").mockImplementation(() => undefined);
});

afterEach(() => {
  vi.restoreAllMocks();
  vi.unstubAllEnvs();
});

describe("prComment payload schema", () => {
  it("rejects payloads without a comment body", () => {
    expect(() =>
      payloadSchema.parse({
        githubToken: "test-token",
        issueNumber: 123,
        owner: "pagopa",
        repo: "dx",
      }),
    ).toThrow();
  });

  it("accepts payloads with a title", () => {
    expect(
      payloadSchema.parse({
        ...payload,
        title: "Build Results",
      }),
    ).toStrictEqual({
      ...payload,
      title: "Build Results",
    });
  });

  it("accepts payloads with a markdown footer", () => {
    expect(
      payloadSchema.parse({
        ...payload,
        footer: "_Generated by dx-tasks_",
      }),
    ).toStrictEqual({
      ...payload,
      footer: "_Generated by dx-tasks_",
    });
  });

  it("rejects payloads with an empty title", () => {
    expect(() =>
      payloadSchema.parse({
        ...payload,
        title: "",
      }),
    ).toThrow();
  });

  it("rejects payloads with an empty footer", () => {
    expect(() =>
      payloadSchema.parse({
        ...payload,
        footer: "",
      }),
    ).toThrow();
  });
});

describe("prComment formatting", () => {
  it("creates a PR comment and returns its metadata", async () => {
    const client = createClient();

    const result = await prComment(payload, {}, client.factory);

    expect(client.factory).toHaveBeenCalledExactlyOnceWith("test-token");
    expect(client.createComment).toHaveBeenCalledExactlyOnceWith(
      {
        issueNumber: 123,
        owner: "pagopa",
        repo: "dx",
      },
      "New test comment",
    );
    expect(result).toStrictEqual({
      commentId: 456,
      commentUrl: "https://github.com/pagopa/dx/issues/123#issuecomment-456",
    });
  });

  it("prefixes the comment body with the title as an H2", async () => {
    const client = createClient();

    await prComment(
      {
        ...payload,
        title: "Build Results",
      },
      {},
      client.factory,
    );

    expect(client.createComment).toHaveBeenCalledExactlyOnceWith(
      {
        issueNumber: 123,
        owner: "pagopa",
        repo: "dx",
      },
      "## Build Results\n\nNew test comment",
    );
  });

  it("appends the footer after a separator", async () => {
    const client = createClient();

    await prComment(
      {
        ...payload,
        footer: "_Generated by dx-tasks_",
      },
      {},
      client.factory,
    );

    expect(client.createComment).toHaveBeenCalledExactlyOnceWith(
      {
        issueNumber: 123,
        owner: "pagopa",
        repo: "dx",
      },
      "New test comment\n\n---\n\n_Generated by dx-tasks_",
    );
  });

  it("appends the footer after the titled comment body", async () => {
    const client = createClient();

    await prComment(
      {
        ...payload,
        footer: "_Generated by dx-tasks_",
        title: "Build Results",
      },
      {},
      client.factory,
    );

    expect(client.createComment).toHaveBeenCalledExactlyOnceWith(
      {
        issueNumber: 123,
        owner: "pagopa",
        repo: "dx",
      },
      "## Build Results\n\nNew test comment\n\n---\n\n_Generated by dx-tasks_",
    );
  });
});

describe("prComment authentication", () => {
  it("uses GITHUB_TOKEN when the payload token is omitted", async () => {
    vi.stubEnv("GITHUB_TOKEN", "env-token");
    const client = createClient();

    await prComment(
      {
        commentBody: "New test comment",
        issueNumber: 123,
        owner: "pagopa",
        repo: "dx",
      },
      {},
      client.factory,
    );

    expect(client.factory).toHaveBeenCalledExactlyOnceWith("env-token");
  });

  it("throws when no GitHub token is available", async () => {
    const client = createClient();

    await expect(
      prComment(
        {
          commentBody: "New test comment",
          issueNumber: 123,
          owner: "pagopa",
          repo: "dx",
        },
        {},
        client.factory,
      ),
    ).rejects.toThrow(
      "GitHub token not found. Please provide githubToken or GITHUB_TOKEN environment variable",
    );
    expect(client.factory).not.toHaveBeenCalled();
  });
});

describe("prComment matching-comment deletion", () => {
  it("deletes comments matching the search pattern case-insensitively before creating the comment", async () => {
    const client = createClient({
      comments: [
        { body: "<!-- test-marker --> Old comment", id: 1 },
        { body: "Some other comment", id: 2 },
        { body: "Another <!-- TEST-MARKER --> comment", id: 3 },
        { body: undefined, id: 4 },
      ],
    });

    await prComment(
      {
        ...payload,
        searchPattern: "TEST-marker",
      },
      {},
      client.factory,
    );

    expect(client.listComments).toHaveBeenCalledExactlyOnceWith({
      issueNumber: 123,
      owner: "pagopa",
      repo: "dx",
    });
    expect(client.deleteComment).toHaveBeenCalledTimes(2);
    expect(client.deleteComment).toHaveBeenNthCalledWith(1, "pagopa", "dx", 1);
    expect(client.deleteComment).toHaveBeenNthCalledWith(2, "pagopa", "dx", 3);
    expect(client.createComment).toHaveBeenCalledOnce();
  });

  it("warns and still creates the comment when matching-comment deletion fails", async () => {
    const client = createClient({
      comments: [{ body: "<!-- test-marker --> Old comment", id: 1 }],
      deleteComment: vi.fn<
        (owner: string, repo: string, commentId: number) => Promise<void>
      >(async () => {
        throw new Error("Comment not found");
      }),
    });

    await prComment(
      {
        ...payload,
        searchPattern: "test-marker",
      },
      {},
      client.factory,
    );

    expect(console.warn).toHaveBeenCalledExactlyOnceWith(
      "Failed to delete existing comments: Comment not found",
    );
    expect(client.createComment).toHaveBeenCalledOnce();
  });
});
