name: "Get All Providers"
description: "Lists all Terraform providers in the repository"

outputs:
  providers:
    description: "List of all providers in the format [\"name1\", \"name2\"]"
    value: ${{ steps.get-all-providers.outputs.providers }}

runs:
  using: "composite"
  steps:
    - name: Get all providers
      id: get-all-providers
      shell: bash
      run: |
        folders_list=$(find apps/providers -mindepth 1 -maxdepth 1 -type d | sed 's#apps/providers/##' | jq -R -c . | jq -s -c .)
        echo "All providers: $folders_list"
        echo "providers=$folders_list" >> $GITHUB_OUTPUT
