name: CDN Code Deploy 
description: Assets deployment to CDN

# This action allows you to deploy the passed asset to the CDN.
# The asset must be the directory that contains all the files you want to sync.

inputs:
  storage_account_name:
    description: Storage account name.
    type: string
    required: true
  blob_container_name:
    description: Blob container name.
    type: string
    required: true
  resource_group_name:
    description: CDN resource group name.
    type: string
    required: true
  profile_name:
    description: CDN Profile name.
    type: string
    required: true
  endpoint_name:
    description: CDN endpoint name.
    type: string
    required: true
  selective_purge_paths:
    description: |
      List of relative paths for files to include in the purge. Leave empty to purge all files.
      Paths should be relative to the synchronized directory (sync_dir_name).
      For example, if syncing ./dist, to include ./dist/path/file1 and ./dist/path/file2, specify "./path/file1 ./path/file2."
      To recursively purge an entire directory, use the pattern "./path/dir/*".

      The format should follow the parameters as described in the official documentation: 
      https://learn.microsoft.com/en-us/cli/azure/cdn/endpoint?view=azure-cli-latest#az-cdn-endpoint-purge-required-parameters
    type: string
    required: false
  sync_dir_name:
    description: Path to the files directory (Default is 'dist')
    type: string
    required: false
    default: 'dist'
  working_directory:
    description: The path of the directory containing the folder to be synchronized (Default is '.')
    type: string
    required: false
    default: '.'
  destination_dir:
    description: The path of the directory where the files will be synchronized in the storage account container (Default is './')
    type: string
    required: false
    default: '.'

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    # ## Sync Storage
    # # will be synced the to the working_directory/sync_dir_name defined (Default will be './dist')
    # - name: Sync Storage
    #   shell: bash
    #   run: |
    #     az storage blob sync \
    #       --container '${{ inputs.blob_container_name }}' \
    #       --account-name ${{ inputs.storage_account_name }} \
    #       --source "${{ env.FOLDER_NAME }}" \
    #       --destination "${{ env.DEST_DIRECTORY }}"
    #   working-directory: ${{ env.WORKING_DIRECTORY }}
    #   env:
    #     FOLDER_NAME: ${{ inputs.sync_dir_name || 'dist' }}
    #     WORKING_DIRECTORY: ${{ inputs.working_directory || '.' }}
    #     DEST_DIRECTORY: ${{ inputs.destination_dir || './' }}

    # ## Purge CDN
    # # If you don't want to purge all files to speed up the step, define selective_purge_paths
    # - name: Purge CDN for selected files
    #   if: ${{ inputs.selective_purge_paths != '' }}
    #   shell: bash
    #   run: |
    #     az cdn endpoint purge \
    #       --resource-group ${{ inputs.resource_group_name }} \
    #       --endpoint-name ${{ inputs.endpoint_name }} \
    #       --profile-name ${{ inputs.profile_name }} \
    #       --content-paths $(echo "${{ inputs.selective_purge_paths }}" | sed -e "s/\([^ ]*\)/'\1'/g")

    # # If selective_purge_paths is not defined, purge all files '/*'
    # - name: Purge CDN
    #   if: ${{ inputs.selective_purge_paths == '' }}
    #   shell: bash
    #   run: |
    #     az cdn endpoint purge \
    #       --resource-group ${{ inputs.resource_group_name }} \
    #       --endpoint-name ${{ inputs.endpoint_name }} \
    #       --profile-name ${{ inputs.profile_name }} \
    #       --content-paths "/*"

    ## Sync Storage
    # will be synced the to the working_directory/sync_dir_name defined (Default will be './dist')
    - name: Sync Storage
      shell: bash
      run: |
        echo "az storage blob sync --container '${{ inputs.blob_container_name }}' --account-name ${{ inputs.storage_account_name }} --source ${{ env.FOLDER_NAME }} --destination ${{ env.DEST_DIRECTORY }}"
      working-directory: ${{ env.WORKING_DIRECTORY }}
      env:
        FOLDER_NAME: ${{ inputs.sync_dir_name || 'dist' }}
        WORKING_DIRECTORY: ${{ inputs.working_directory || '.' }}
        DEST_DIRECTORY: ${{ inputs.destination_dir || './' }}

    ## Purge CDN
    # If you don't want to purge all files to speed up the step, define selective_purge_paths
    - name: Purge CDN for selected files
      if: ${{ inputs.selective_purge_paths != '' }}
      shell: bash
      run: |
        echo 'az cdn endpoint purge --resource-group ${{ inputs.resource_group_name }} --endpoint-name ${{ inputs.endpoint_name }} --profile-name ${{ inputs.profile_name }}'
        $(echo "${{ inputs.selective_purge_paths }}" | sed -e "s/\([^ ]*\)/'\1'/g")

    # If selective_purge_paths is not defined, purge all files '/*'
    - name: Purge CDN
      if: ${{ inputs.selective_purge_paths == '' }}
      shell: bash
      run: |
        echo 'az cdn endpoint purge --resource-group ${{ inputs.resource_group_name }} --endpoint-name ${{ inputs.endpoint_name }} --profile-name ${{ inputs.profile_name }} --content-paths "/*"'