# Removed blocks for GitHub repository resources that are now managed by the repository module
# Generated by Azure GitHub Environment Bootstrap migration script
#
# INSTRUCTIONS:
# 1. Run 'terraform plan' to see what will be removed from this module
# 2. Run 'terraform apply' to execute the removals (resources won't be destroyed)
# 3. After successful migration, you can delete this file
#
# NOTE: The lifecycle.destroy = false ensures resources are only removed from state,
# not actually destroyed in GitHub

# Remove the main GitHub repository resource from this module's state
removed {
  from = module.bootstrapper.module.bootstrap.github_repository.this
  lifecycle {
    destroy = false
  }
}

# Remove the GitHub repository module and its nested resources from this module's state
removed {
  from = module.bootstrapper.module.bootstrap.module.github_repository.github_repository.this
  lifecycle {
    destroy = false
  }
}

removed {
  from = module.bootstrapper.module.bootstrap.module.github_repository.github_actions_repository_permissions.repo
  lifecycle {
    destroy = false
  }
}

removed {
  from = module.bootstrapper.module.bootstrap.module.github_repository.github_branch_default.main
  lifecycle {
    destroy = false
  }
}

removed {
  from = module.bootstrapper.module.bootstrap.module.github_repository.github_branch_protection.main
  lifecycle {
    destroy = false
  }
}

removed {
  from = module.bootstrapper.module.bootstrap.module.github_repository.null_resource.workflow_permissions
  lifecycle {
    destroy = false
  }
}

# Remove all infra_cd environments from this module's state
removed {
  from = module.bootstrapper.module.bootstrap.github_repository_environment.infra_cd
  lifecycle {
    destroy = false
  }
}

# Remove all app_cd environments from this module's state
removed {
  from = module.bootstrapper.module.bootstrap.github_repository_environment.app_cd
  lifecycle {
    destroy = false
  }
}

# Remove all opex_cd environments from this module's state
removed {
  from = module.bootstrapper.module.bootstrap.github_repository_environment.opex_cd
  lifecycle {
    destroy = false
  }
}

# Remove all infra_ci environments from this module's state
removed {
  from = module.bootstrapper.module.bootstrap.github_repository_environment.infra_ci
  lifecycle {
    destroy = false
  }
}

# Remove all opex_ci environments from this module's state
removed {
  from = module.bootstrapper.module.bootstrap.github_repository_environment.opex_ci
  lifecycle {
    destroy = false
  }
}

# Remove all app_cd_branch deployment policies from this module's state
removed {
  from = module.bootstrapper.module.bootstrap.github_repository_environment_deployment_policy.app_cd_branch
  lifecycle {
    destroy = false
  }
}

# Remove all infra_cd_branch deployment policies from this module's state
removed {
  from = module.bootstrapper.module.bootstrap.github_repository_environment_deployment_policy.infra_cd_branch
  lifecycle {
    destroy = false
  }
}

# Remove all opex_cd_branch deployment policies from this module's state
removed {
  from = module.bootstrapper.module.bootstrap.github_repository_environment_deployment_policy.opex_cd_branch
  lifecycle {
    destroy = false
  }
}

