name: "Upload Artifact"
description: "Upload an artifact to the workflow run"

inputs:
  file_path:
    description: "Path of the file to upload (Example: ./build/bundle.zip)"
    type: string
    required: true
  bundle_name:
    description: "Name of the bundle to upload"
    type: string
    required: true

runs:
  using: "composite"

  steps:
    - name: Upload Artifact
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: ${{ inputs.bundle_name }}
        path: ${{ inputs.file_path }}
        if-no-files-found: error
        retention-days: 7
