name: "Upload Artifact"
description: "Upload an artifact to the workflow run"

inputs:
  file_path:
    description: "Path of the file to upload (Example: ./build/bundle.zip)"
    required: true
  bundle_name:
    description: "Name of the bundle to upload"
    required: true
  include-hidden-files:
    description: "Whether to include hidden files in the provided path in the artifact"
    required: false
  retention-days:
    description: "Duration after which artifact will expire in days. Default is 7 days."
    required: false

runs:
  using: "composite"

  steps:
    - name: Upload Artifact
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
      with:
        name: ${{ inputs.bundle_name }}
        path: ${{ inputs.file_path }}
        if-no-files-found: error
        retention-days: ${{ inputs.retention-days || 7 }}
        include-hidden-files: ${{ inputs.include-hidden-files || false }}
