name: "Detect Node.js Package Manager"
description: "This action detects the Node.js package manager used in the repository."

outputs:
  package-manager:
    description: "The detected package manager (npm, yarn, pnpm)"
    value: ${{ steps.detect-pm.outputs.package-manager }}

runs:
  using: composite
  steps:
    - name: Detect package manager
      id: detect-pm
      shell: bash
      run: |
        write_output() {
          echo "package-manager=$1" >> "$GITHUB_OUTPUT"
          echo "Detected package manager: $1"
          if [ "$1" != "pnpm" ]; then
            echo "::warning::Starting January 16th, 2026, yarn and npm will no longer be supported by this workflow. All new builds will be required to use pnpm, read more at https://dx.pagopa.it/blog/migrating-to-pnpm/"
          fi
          exit 0
        }

        # First, try to detect from package.json packageManager field
        if [ -f "package.json" ]; then
          PACKAGE_MANAGER=$(jq -r '.packageManager // empty' package.json 2>/dev/null | cut -d'@' -f1)
          if [ -n "$PACKAGE_MANAGER" ]; then
            write_output "$PACKAGE_MANAGER"
            exit 0
          fi
        fi

        # Fall back to lock file detection
        if [ -f "yarn.lock" ]; then
          write_output "yarn"
        elif [ -f "pnpm-lock.yaml" ]; then
          write_output "pnpm"
        elif [ -f "package-lock.json" ]; then
          write_output "npm"
        else
          echo "No package manager detected, defaulting to npm"
          write_output "npm"
        fi
