name: Download Terraform Plan
description: Downloads and decrypts a Terraform plan artifact

inputs:
  plan-file:
    description: Name of the Terraform plan file to decrypt
    required: true
  working-directory:
    description: Working directory where the plan will be decrypted
    required: true
  artifact-name:
    description: Name of the artifact to download
    required: true

runs:
  using: composite
  steps:
    - name: Download Terraform Plan Artifact
      uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.working-directory }}

    - name: Decrypt Terraform Plan
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        PLAN_FILE: ${{ inputs.plan-file }}
        ENCRYPTION_PASSPHRASE: ${{ env.ARTIFACT_ENC_KEY }}
      run: |
        set -euo pipefail
        openssl enc -aes-256-cbc -d -pbkdf2 \
          -in "${PLAN_FILE}.enc" \
          -out "$PLAN_FILE" \
          -pass env:ENCRYPTION_PASSPHRASE
        rm -f "${PLAN_FILE}.enc"
