name: Validate GitHub Pages Website

on:
  pull_request:
    branches:
      - main
    paths:
      - "website/**"

# env:
#   WORKING_DIR: ./website

# defaults:
#   run:
#     working-directory: ./website

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup yarn
        run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Setup turbo cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: node_modules/.cache/turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Test build website
        run: yarn run build
