name: "Cloud Login"
description: "Login to cloud provider (Azure or AWS) based on available secrets"

runs:
  using: "composite"

  steps:
    - name: Check AWS and Azure credentials
      shell: bash
      run: |
        if [ -z "$ROLE_ARN" ] && { [ -z "$ARM_CLIENT_ID" ] || [ -z "$ARM_TENANT_ID" ] || [ -z "$ARM_SUBSCRIPTION_ID" ]; }; then
          echo "No cloud credentials provided. Please set either ROLE_ARN for AWS or ARM_CLIENT_ID, ARM_TENANT_ID, and ARM_SUBSCRIPTION_ID for Azure."
          exit 1
        fi

    - name: Azure Login
      if: env.ARM_CLIENT_ID && env.ARM_TENANT_ID && env.ARM_SUBSCRIPTION_ID
      uses: pagopa/dx/.github/actions/azure-login@main

    - name: AWS Login
      if: env.ROLE_ARN
      uses: pagopa/dx/.github/actions/aws-login@main
