name: "Terraform Setup"
description: "Setup Terraform and initialize the working directory"

inputs:
  terraform_version:
    description: "Specify the Terraform version to use, if not set, it will be read from .terraform-version file"
    required: false

outputs:
  terraform_version:
    description: "The Terraform version that was used"
    value: ${{ steps.set-terraform-version.outputs.terraform_version }}

runs:
  using: "composite"

  steps:
    - name: Get Terraform Version
      if: ${{ inputs.terraform_version == '' }}
      id: get-version
      uses: pagopa/dx/.github/actions/get-terraform-version@main
      with:
        override_version: ${{ inputs.terraform_version }}

    - uses: hashicorp/setup-terraform@a1502cd9e758c50496cc9ac5308c4843bcd56d36 # v3.0.0
      name: Setup Terraform
      with:
        terraform_version: ${{ inputs.terraform_version || steps.get-version.outputs.terraform_version }}
