name: NodeJS CDN Code Build 
description: An action to build the artifact to the CDN

inputs:
  workspace_name:
    description: The name of the workspace to create the artifact for.
    type: string
    required: true
  custom_env_config_variables:
    description: Contain variable for env-config.js file generation (Optional)
    type: string
    required: false
  bundle_name:
    description: Name of the bundle
    type: string
    required: false
  base_workdir:
    description: The base workdir (Default is ./out)
    type: string
    required: false
runs:
  using: composite
  env:
    WORKSPACE: ${{ inputs.workspace_name }}
    BUNDLE_NAME: ${{ inputs.bundle_name == '' && 'bundle' || inputs.bundle_name }}
    BASE_WORKDIR: ${{ inputs.base_workdir == '' && './out' || inputs.base_workdir }}
  steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      name: Checkout

    # - name: Prune
    #   run: npx turbo@1.13.3 prune --scope ${{ env.WORKSPACE }}

    # - name: Setup yarn
    #   run: corepack enable

    - name: Setup Node.js
      uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
      with:
        node-version-file: ".node-version"
        cache: "yarn"
        cache-dependency-path: "${{ env.BASE_WORKDIR }}/yarn.lock"

    - name: Install dependencies
      run: yarn install --immutable
      working-directory: ${{ env.BASE_WORKDIR }}
    
    # This variable have the form "key=value" e.g.
    # VAR_1=VALUE_1
    # VAR_2=VALUE_2
    # VAR_N=VALUE_N
    - name: Define env-config.js
      if: ${{ inputs.custom_env_config_variables }}
      working-directory: ${{ env.BASE_WORKDIR }}
      run: |
        # Recreate config file
        rm -rf ./env-config.js
        touch ./env-config.js

        # Add assignment
        echo "window._env_ = {" >> ./env-config.js

        # Loop on input variables and add them to env-config.js
        INPUT_VARS="${{ inputs.custom_env_config_variables }}"

        while IFS='=' read -r k v; do
            # Ignore empty lines
            if [ -n "$k" ]; then
                echo "  $k: \"$v\"," >> ./env-config.js
            fi
        done <<< "$INPUT_VARS"

        echo "}" >> ./env-config.js

    - name: Build
      run: yarn build
      working-directory: ${{ env.BASE_WORKDIR }}

    - name: Upload Artifact
      uses: actions/upload-artifact@694cdabd8bdb0f10b2cea11669e1bf5453eed0a6 # v4.2.0
      with:
        name: ${{ env.BUNDLE_NAME }}
        path: "${{ env.BASE_WORKDIR }}"
        if-no-files-found: error
        retention-days: 7