name: "Node Setup"
description: "Setup Node.js and Turbo cache"

inputs:
  turbo_cache_dir:
    description: "Specify the turbo cache directory"
    type: string
    required: false
    default: ""
  working_dir:
    description: "Specify the working directory"
    type: string
    required: false
    default: "."

runs:
  using: "composite"

  steps:
    - name: Setup yarn
      shell: bash
      run: corepack enable

    - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b #v4.0.3
      with:
        node-version-file: ".node-version"
        cache: yarn
        cache-dependency-path: "${{ inputs.working_dir }}/yarn.lock"

    - name: Setup turbo cache
      if: ${{ inputs.turbo_cache_dir != '' }}
      uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 #v4.2.0
      with:
        path: ${{ inputs.turbo_cache_dir }}
        key: ${{ runner.os }}-turbo-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-turbo-

    - name: Install dependencies
      shell: bash
      run: yarn install --immutable
      working-directory: ${ inputs.working_dir }
      