name: "Node Setup"
description: "Setup Node.js and Turbo cache"

# To start the turbo cache, set the TURBO_CACHE_DIR environment variable to the directory where you want to store the cache.
# For example, you can set it to .turbo-cache in your project directory.

inputs:
  working_dir:
    description: "Specify the working directory"
    required: false
    default: "."

outputs:
  package-manager:
    description: "The detected package manager (npm, yarn, pnpm)"
    value: ${{ steps.detect-pm.outputs.package-manager }}

runs:
  using: "composite"

  steps:
    - name: Setup yarn
      shell: bash
      run: corepack enable

    - name: Detect Node.js package manager
      id: detect-pm
      uses: pagopa/dx/actions/detect-node-package-manager@main

    - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version-file: .node-version
        cache: ${{ steps.detect-pm.outputs.package-manager }}

    - name: Setup turbo cache
      if: ${{ env.TURBO_CACHE_DIR != '' }}
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: ${{ inputs.working_dir }}/${{ env.TURBO_CACHE_DIR }}
        key: ${{ runner.os }}-turbo-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-turbo-

    - name: Export Package Manager
      shell: bash
      env:
        package_manager: ${{ steps.detect-pm.outputs.package-manager }}
      run: |
        echo "NODE_PACKAGE_MANAGER=$package_manager" >> "$GITHUB_ENV"
