name: "Get Modified Modules"
description: "Determines which Terraform modules have been modified compared to the default branch"

inputs:
  current_ref:
    description: "Current branch reference"
    required: false
    type: string
    default: ""

outputs:
  modules:
    description: "List of modified modules in the format [\"name1\", \"name2\"]"
    value: ${{ steps.get-modules.outputs.modules }}

runs:
  using: "composite"
  steps:
    - name: Get modified modules
      id: get-modules
      shell: bash
      run: |
        DEFAULT_BRANCH_SHA=$(git rev-parse origin/$(git remote show origin | awk '/HEAD branch/ {print $NF}'))
        echo "Default branch SHA: $DEFAULT_BRANCH_SHA"
        CURRENT_BRANCH_SHA=${{ inputs.current_ref || github.sha }}

        folders_list=$(git diff --name-only $DEFAULT_BRANCH_SHA $CURRENT_BRANCH_SHA infra/modules | xargs -r dirname | sed 's#^infra\/modules/\([^/]*\).*#\1#' | uniq | jq -R -c . | jq -s -c .)
        echo Modules changed: $folders_list
        echo "modules=$folders_list" >> $GITHUB_OUTPUT
