name: Build GitHub Self-Hosted Runner

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - feat-create-new-docker-image-self-hosted-runner # for testing purposes

jobs:
  github_runner:
    uses: ./.github/workflows/docker_image_build.yaml
    name: GitHub Self-Hosted Runner
    permissions:
      contents: read
      actions: read
      id-token: write
    secrets: inherit
    with:
      dockerfile_path: './self-hosted-runner/Dockerfile'
      dockerfile_context: './self-hosted-runner'
      docker_image_name: 'dx-github-self-hosted-runner'
      image_description: 'DX GitHub Self-Hosted Runner'
      image_authors: 'DevEx'
      build_platforms: linux/amd64