name: Drift Detection

on:
  workflow_dispatch:
  schedule:
      - cron: '00 08 * * *' # Run at 08:00 every day

jobs:
  drift_detection_dev:
    uses: ./.github/workflows/infra_drift_detection.yml
    name: Drift Detection
    permissions:
      contents: read
      actions: read
      id-token: write
    secrets: inherit
    with:
      environment: 'dev'
      override_github_environment: 'infra-dev'
      base_path: 'infra/resources'

  drift_detection_prod:
    uses: ./.github/workflows/infra_drift_detection.yml
    name: Drift Detection
    permissions:
      contents: read
      actions: read
      id-token: write
    secrets: inherit
    with:
      environment: 'prod'
      override_github_environment: 'infra-prod'
      base_path: 'infra/resources'