name: Nx Release

on:
  push:
    branches:
      - main
    paths:
      - ".nx/version-plans/**"
  pull_request:
    types:
      - closed
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  version-packages-pr:
    if: github.event_name == 'push'
    name: Create/Update Version Packages PR
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    uses: ./.github/workflows/release-v1.yaml
    with:
      environment: npm-prod-cd
      mode: "create-pr"
    secrets:
      github-token: ${{ secrets.BOT_GH_TOKEN }}

  release:
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'nx-release/')
    name: Publish Release
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    uses: ./.github/workflows/release-v1.yaml
    with:
      environment: npm-prod-cd
      mode: "publish"
    secrets:
      github-token: ${{ secrets.BOT_GH_TOKEN }}
