name: Devcontainer Features (Publish)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/_release-docker-devcontainer-features.yaml"
      - ".devcontainer/features/**"

jobs:
  publish_features:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Publish Features
        uses: devcontainers/action@1082abd5d2bf3a11abccba70eef98df068277772 # v1.4.3
        with:
          publish-features: "true"
          base-path-to-features: .devcontainer/features
          features-namespace: pagopa/devcontainer-features
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
