name: Deploy Static Site to Azure - TEST

on:
  # push:
  #   branches:
  #     - feat-dx-docs-on-static-app-poc # main
  # pull_request:
  #   types: [opened, synchronize, reopened, closed]
  #   branches:
  #     - feat-dx-docs-on-static-app-poc # main
  workflow_dispatch:

jobs:
  build_and_deploy:
    # if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    environment: infra-dev-cd
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          fetch-depth: 0

      - name: Node Setup
        uses: pagopa/dx/.github/actions/node-setup@main

      - name: Install dependencies
        run: pnpm install
        working-directory: ./apps/website

      - name: Build website
        run: pnpm build
        working-directory: ./apps/website

      - name: Azure Login
        uses: pagopa/dx/.github/actions/azure-login@main
        env:
          ARM_USE_OIDC: true
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: Find API Key
        id: find_api_key
        run: |
          api_key=$(az staticwebapp secrets list --name dx-d-itn-static-app-test-app-01 --resource-group dx-d-itn-test-rg-01 | jq -r '.properties.apiKey')
          echo "::add-mask::$api_key"
          echo "sensitive-value=$api_key" >> $GITHUB_OUTPUT

      - name: Build and Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ steps.find_api_key.outputs.sensitive-value }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          
          app_location: "/apps/website/build"
          api_location: ""