name: Deploy MCP Server
description: |
  Automated workflow to build MCP Server Docker image and deploy it to
  AWS Lambda when changes are made or new tags are pushed

on:
  workflow_dispatch:
  push:
    tags:
      - "@pagopa/dx-mcpserver@*"
    # branches:
    #   - feat-action-for-mcp-deploy

jobs:
  build:
    name: Build MCP Docker Image
    runs-on: ubuntu-latest
    environment: infra-dev-ci # cd
    env:
      AWS_REGION: eu-central-1
      ROLE_ARN: ${{ secrets.ROLE_ARN }}
      LAMBDA_FUNCTION_NAME: dx-p-euc1-mcp-server-lambda-01
      IMAGE_NAME: dx/mcp-server
    permissions:
      id-token: write
      contents: read
      packages: read

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Cloud Login
        uses: pagopa/dx/actions/csp-login@main

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1

      - name: Docker Build and Push to GHCR
        uses: pagopa/dx/.github/actions/docker-build-push@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          dockerfile_path: "apps/mcpserver/Dockerfile"
          docker_image_name: "${{ env.IMAGE_NAME }}"
          docker_image_description: "DX MCP Server Docker Image"
          docker_image_authors: "PagoPA DX"
          build_platforms: linux/amd64
          push_to_registry: true

      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull from GHCR and Push to ECR
        id: push-ecr
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
          GHCR_IMAGE: ghcr.io/${{ env.IMAGE_NAME }}
        run: |
          # Pull the image from GitHub Container Registry
          echo "Pulling image from GHCR..."
          docker pull $GHCR_IMAGE:$IMAGE_TAG

          # Tag for ECR with both commit SHA and latest
          ECR_IMAGE_URI="$ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG"
          ECR_IMAGE_LATEST="$ECR_REGISTRY/$IMAGE_NAME:latest"

          echo "Tagging images for ECR..."
          docker tag $GHCR_IMAGE:$IMAGE_TAG $ECR_IMAGE_URI
          docker tag $GHCR_IMAGE:$IMAGE_TAG $ECR_IMAGE_LATEST

          # Push to ECR
          echo "Pushing to ECR..."
          docker push $ECR_IMAGE_URI
          docker push $ECR_IMAGE_LATEST

          echo "image-uri=$ECR_IMAGE_URI" >> $GITHUB_OUTPUT
          echo "✅ Image pulled from GHCR and pushed to ECR: $ECR_IMAGE_URI"

      - name: Deploy Lambda
        uses: aws-actions/aws-lambda-deploy@29ea35c124579506cf0475e20df36198eb670d89 # v1.1.0
        with:
          function-name: ${{ env.LAMBDA_FUNCTION_NAME }}
          package-type: Image
          image-uri: ${{ steps.push-ecr.outputs.image-uri }}
