name: Push Provider to Subrepo
# This workflow is triggered on changes to the terraform provider and pushes the changes to the subrepository.

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "infra/provider/**"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  push-provider:
    runs-on: ubuntu-latest
    if: always()
    permissions:
      contents: read
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - name: Push provider to subrepository
        id: push-to-subrepository
        uses: ./.github/actions/push-to-subrepo
        with:
          name: "azure"
          repo_type: "provider"
          github_pat: ${{ secrets.PUSH_TF_MODULES_PAT }}
