name: Deploy DX Metrics Container App

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "apps/dx-metrics/package.json"

permissions:
  contents: read
  id-token: write
  packages: write
  attestations: write

jobs:
  deploy:
    name: Deploy DX Metrics as Container App
    concurrency:
      group: ${{ github.workflow }}-cd
      # Override this configuration to prevent cancelling a running deploy.
      cancel-in-progress: false
    uses: pagopa/dx/.github/workflows/release-azure-containerapp-v1.yaml@upgrade-docker-push-action
    secrets: inherit
    with:
      dockerfile_path: ./apps/dx-metrics/Dockerfile
      dockerfile_context: .
      docker_image_name: pagopa/dx-metrics
      docker_image_description: "DX Metrics is a monitoring and analytics service for the PagoPA Developer Experience (DX) team, providing insights into development experience."
      container_app: dx-p-itn-metrics-portal-ca-01
      resource_group_name: dx-p-itn-common-rg-01
      environment: app-prod
