name: Terraform apply on dev resources

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "infra/resources/dev/**"
      - "infra/resources/_modules/**"
      - ".github/workflows/_release-terraform-apply-dev-resources.yaml"
jobs:
  dev_itn_common_deploy:
    uses: pagopa/dx/.github/workflows/infra_apply.yaml@main
    name: Dev - Deploy
    secrets: inherit
    with:
      environment: dev
      base_path: "infra/resources/"
      override_github_environment: infra-dev
      use_private_agent: true
