name: Deploy DX Metrics Container App

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: Released DX Metrics image version to deploy
        required: true
        type: string
  push:
    # Scope production deployment to the Nx release tag for this project.
    tags:
      - "dx-metrics@*"

permissions:
  contents: read
  id-token: write
  packages: write
  attestations: write

jobs:
  deploy:
    name: Deploy DX Metrics as Container App
    concurrency:
      group: ${{ github.workflow }}-cd
      # Override this configuration to prevent cancelling a running deploy.
      cancel-in-progress: false
    uses: pagopa/dx/.github/workflows/release-azure-containerapp-v1.yaml@main
    secrets: inherit
    with:
      docker_image_name: pagopa/dx-metrics
      docker_image_tag: ${{ inputs.image_tag || github.ref_name }}
      container_app: dx-p-itn-metrics-portal-ca-01
      resource_group_name: dx-p-itn-common-rg-01
      environment: app-prod
