name: Devcontainer Templates (Publish)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/devcontainer_publish_templates.yaml"
      - ".devcontainer/templates/**"

jobs:
  publish_templates:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Publish Templates
        uses: devcontainers/action@1082abd5d2bf3a11abccba70eef98df068277772 # v1.4.3
        with:
          publish-templates: "true"
          base-path-to-templates: .devcontainer/templates
          templates-namespace: pagopa/devcontainer-templates
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
