name: "Code Review"

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  validate:
    if: ${{ github.actor != 'dx-pagopa-bot' }}
    permissions:
      contents: read
      actions: read
      pull-requests: write
      id-token: write
    uses: ./.github/workflows/validate-v2.yaml
    secrets: inherit
