name: Terraform Provider Tests

on:
  pull_request:
    paths:
      - '.github/workflows/_validate-go-test-provider.yaml'
      - 'infra/provider/**'

permissions:
  contents: read

env:
  GO_MOD_PATH: 'infra/provider/go.mod'
  WORKSPACE: 'infra/provider'

jobs:
  acceptance:
    name: Acceptance Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version-file: '${{ env.GO_MOD_PATH }}'

      - name: Terraform Setup
        id: set-terraform-version
        uses: pagopa/dx/.github/actions/terraform-setup@main

      - name: Run Tests
        run: make testacc
        working-directory: '${{ env.WORKSPACE }}'