name: "Code Review"

on:
  workflow_dispatch:

jobs:
  validate:
    if: ${{ github.actor != 'dx-pagopa-bot' }}
    permissions:
      contents: read
      actions: read
      pull-requests: write
      id-token: write
    uses: ./.github/workflows/validate-v1.yaml
    secrets:
      app-client-id: ${{ secrets.GH_APP_RELEASE_CLIENT_ID }}
      app-private-key: ${{ secrets.GH_APP_RELEASE_APP_KEY }}
