name: Terraform plan on prod resources

on:
  merge_group:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - "infra/resources/prod/**"
      - "infra/resources/_modules/**"
      - ".github/workflows/_validate-terraform-plan-resources.yaml"

jobs:
  code_review:
    uses: pagopa/dx/.github/workflows/infra_plan.yaml@main
    name: Terraform Plan
    secrets: inherit
    with:
      environment: prod
      base_path: "infra/resources/"
      use_private_agent: true
