name: Deploy PR Preview for Docusaurus Website

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "apps/website/**"
      - ".github/workflows/_validate-docusaurus-pr-preview.yaml"

# Set default working directory for all run steps
defaults:
  run:
    working-directory: ./apps/website
env:
  PREVIEW_BRANCH: gh-pages

jobs:
  build-and-preview:
    # Don't run in Changeset PRs
    if: ${{ github.actor != 'dx-pagopa-bot' || github.event_name == 'workflow_dispatch' }}
    name: Build and Deploy PR Preview
    runs-on: ubuntu-latest

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
      contents: write # to write the repository contents

    env:
      TURBO_CACHE_DIR: .turbo-cache
      PR_PREVIEW: 'true'
      PR_NUMBER: ${{ github.event.number }}

    steps:
      - name: Check out code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
        with:
          fetch-depth: 0

      - name: Node Setup
        uses: pagopa/dx/.github/actions/node-setup@main

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build website
        run: yarn run build

      - name: Deploy PR Preview
        id: preview-step
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./apps/website/build
          preview-branch: "${{ env.PREVIEW_BRANCH }}"
          umbrella-dir: pr-preview
          action: auto

      - uses: marocchino/sticky-pull-request-comment@v2
        if: steps.preview-step.outputs.deployment-action == 'deploy' && env.deployment_status == 'success'
        with:
          header: pr-preview
          message: |
            [PR Preview Action](https://github.com/rossjrw/pr-preview-action) ${{ steps.preview-step.outputs.action-version }}
            :---:
            | <p></p> :rocket: View preview at <br> ${{ steps.preview-step.outputs.preview-url }} <br><br>
            | <h6>Built to branch [`${{ env.PREVIEW_BRANCH }}`](${{ github.server_url }}/${{ github.repository }}/tree/${{ env.PREVIEW_BRANCH }}) at ${{ steps.preview-step.outputs.action-start-time }}. <br> Preview will be ready when the [GitHub Pages deployment](${{ github.server_url }}/${{ github.repository }}/deployments) is complete. <br><br> </h6>

      - uses: marocchino/sticky-pull-request-comment@v2
        if: steps.preview-step.outputs.deployment-action == 'remove' && env.deployment_status == 'success'
        with:
          header: pr-preview
          message: |
            [PR Preview Action](https://github.com/rossjrw/pr-preview-action) ${{ steps.preview-step.outputs.action-version }}
            :---:
            Preview removed because the pull request was closed.
            ${{ steps.preview-step.outputs.action-start-time }}
