name: CDN - TEST

on:
  workflow_dispatch:
  push:
    branches:
      - DEVEX-165-cdn-workflow

jobs:
  test_cdn_deploy:
    uses: ./.github/workflows/cdn_app_deploy.yaml
    name: Test CDN Deploy
    secrets: inherit
    with:
      workspace_name: '.'
      environment: 'dev'
      resource_group_name: 'io-test-rg-01'
      storage_account_name: 'io-test-sa-01'
      profile_cdn_name: 'io-test-dev-cdn-01'
      endpoint_name: 'io-test-dev-cdn-01'
      blob_container_name: 'io-test-dev-cdn-01'
      selective_purge_paths: "'/path/file1' '/path/file2'"
      use_private_agent: 'false'

