name: CDN - TEST

on:
  workflow_dispatch:
  push:
    branches:
      - DEVEX-165-cdn-workflow


jobs:
  test:
    name: test
    runs-on: ubuntu-22.04
    environment: dev-cd
    permissions:
      id-token: write
      contents: read
      actions: read
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        name: Checkout

      - name: Azure Login
        uses: azure/login@v2 # v2.0.0
        env:
          ARM_USE_OIDC: true
        with:
          client-id: ${{ env.ARM_CLIENT_ID }}
          tenant-id: ${{ env.ARM_TENANT_ID }}
          subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}

      - uses: ./.github/actions/cdn_code_deploy
        name: Test CDN Deploy
        with:
          working_directory: '.'
          sync_folder_name: 'website'
          resource_group_name: 'io-test-rg-01'
          storage_account_name: 'io-test-sa-01'
          profile_cdn_name: 'io-test-dev-cdn-01'
          endpoint_name: 'io-test-dev-cdn-01'
          blob_container_name: 'io-test-dev-cdn-01'
          selective_purge_paths: "./path/file1 ./path/file2"
