name: Code Review

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    paths:
      - apps/**
      - packages/**

jobs:
  js_code_review:
    uses: ./.github/workflows/js_code_review.yaml
    name: Code Review
    secrets: inherit