name: Cleanup DEV Resources

on:
  workflow_dispatch:
  push:
    branches:
      - CES-525-define-delete-dev-resources

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  get-modified-modules:
    uses: ./.github/workflows/_cleanup_resources.yaml
    name: Cleanup DEV Resources
    with:
      environment: "Dev"
      ttl: 30