name: Cleanup DEV Resources

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  get-modified-modules:
    uses: ./.github/workflows/_cleanup_resources.yaml
    name: Cleanup DEV Resources
    with:
      environment: "dev"
      ttl: 30