on:
  workflow_call:
    inputs:
      workspace_name:
        type: string
        required: true
        description: The name of the workspace to create the artifact for.
      environment:
        description: Environment where the artifact will be deployed.
        type: string
        required: true
      resource_group_name:
        description: Function App resource group name.
        type: string
        required: true
      function_app_name:
        description: Function App name.
        type: string
        required: true
      health_check_path:
        description: The health probe path exposed by the Function App.
        type: string
        required: true
      use_staging_slot:
        description: True if artifact should be deployed to staging slot
        type: boolean
        required: false
        default: true
      use_private_agent:
        description: Use a private agent to deploy the built artifact.
        type: boolean
        required: false
        default: true
      use_labels:
        description: Use labels to start the right environment's GitHub runner. If use_labels is true, also use_private_agent must be set to true
        type: boolean
        required: false
        default: false
      override_labels:
        description: Needed for special cases where the environment alone is not sufficient as a distinguishing label
        type: string
        required: false
        default: ''

concurrency:
  group: ${{ github.workflow }}-cd
  cancel-in-progress: true

env:
  BUNDLE_NAME: bundle

jobs:

  build:
    name: Build Artifact
    runs-on: ubuntu-latest
    env:
      WORKSPACE: ${{ inputs.workspace_name }}
      TURBO_CACHE_DIR: .turbo-cache

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        name: Checkout

      - name: Detect turbo version
        id: turbo-version
        run: |
          TURBO_VERSION=$(jq -r '.devDependencies.turbo | split(".") | .[0]' package.json)
          echo "version=$TURBO_VERSION" >> $GITHUB_OUTPUT

      - name: Prune (turbo 1.x)
        if: steps.turbo-version.outputs.version == '1'
        run: |
          npx turbo@1.13.3 prune --scope ${{ env.WORKSPACE }}
          echo "::warning::Turbo 1.x is deprecated. Please upgrade to the latest version."

      - name: Prune
        if: steps.turbo-version.outputs.version != '1'
        run: npx turbo prune --scope ${{ env.WORKSPACE }}

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b #v4.0.3
        with:
          node-version-file: ".node-version"
          cache: "yarn"
          cache-dependency-path: "./out/yarn.lock"

      # we fall back to node-moules, even in case pnp is configured, in order to avoid bundling dependendencies
      - name: Install dependencies
        run: |
          yarn config set nodeLinker node-modules
          yarn config set nmHoistingLimits workspaces
          yarn install --immutable
        working-directory: ./out

      - name: Restore turbo cache
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 #v4.2.0
        with:
          path: ./out/${{ env.TURBO_CACHE_DIR }}
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo

      - name: Build
        run: yarn build
        working-directory: ./out

      - name: Build the Function App Artifact
        id: make-function-app-artifact
        run: |
          npm pkg set --json "bundledDependencies"=true
          npm pkg set --json "files"='["**/function.json", "dist", "host.json","extensions.csproj"]'
          npx npm-pack-zip
          mv $(jq -r .name package.json).zip ${{ env.BUNDLE_NAME }}.zip
          echo "artifact-path=$(realpath ${{ env.BUNDLE_NAME }}.zip)" >> "$GITHUB_OUTPUT"
        working-directory: ./out/apps/${{ env.WORKSPACE }}

      - name: Upload Artifact
        uses: actions/upload-artifact@694cdabd8bdb0f10b2cea11669e1bf5453eed0a6 # v4.2.0
        with:
          name: ${{ env.BUNDLE_NAME }}
          path: ${{ steps.make-function-app-artifact.outputs.artifact-path }}
          if-no-files-found: error
          retention-days: 7

  deploy:
    name: Deploy
    if: ${{ !github.event.act }}
    needs: [build]
    # Use inputs.override_labels if set; otherwise, fall back to inputs.environment.
    # When inputs.use_labels and inputs.use_private_agent are true, apply the selected labels.
    # Default to 'self-hosted' if inputs.use_private_agent is true, or 'ubuntu-latest' otherwise.
    runs-on: ${{ inputs.use_labels && inputs.use_private_agent && (inputs.override_labels != '' && inputs.override_labels || inputs.environment) || inputs.use_private_agent && 'self-hosted' || 'ubuntu-latest' }}
    environment: ${{ inputs.environment }}-cd
    permissions:
      id-token: write
      contents: read
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_USE_OIDC: true
      RESOURCE_GROUP_NAME: ${{ inputs.resource_group_name }}
      FUNCTION_APP_NAME: ${{ inputs.function_app_name}}
      HEALTH_CHECK_PATH: ${{ inputs.health_check_path }}
      USE_STAGING_SLOT: ${{ inputs.use_staging_slot }}

    steps:

      - name: Download Artifact
        uses: actions/download-artifact@6b208ae046db98c579e8a3aa621ab581ff575935 # v4.1.1
        with:
          name: ${{ env.BUNDLE_NAME }}

      - name: Azure Login
        uses: azure/login@a65d910e8af852a8061c627c456678983e180302 # v2
        with:
          client-id: ${{ env.ARM_CLIENT_ID }}
          tenant-id: ${{ env.ARM_TENANT_ID }}
          subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}

      - name: Deploy
        uses: azure/webapps-deploy@4bfb30bef2c330e36be280cb1e5726d0fac06233 # v2
        if: ${{ env.USE_STAGING_SLOT == 'false' }}
        with:
          resource-group-name: ${{ env.RESOURCE_GROUP_NAME }}
          app-name: ${{ env.FUNCTION_APP_NAME }}
          package: ${{ env.BUNDLE_NAME }}.zip

      - name: Deploy to Staging Slot
        uses: azure/webapps-deploy@4bfb30bef2c330e36be280cb1e5726d0fac06233 # v2
        if: ${{ env.USE_STAGING_SLOT == 'true' }}
        with:
          resource-group-name: ${{ env.RESOURCE_GROUP_NAME }}
          app-name: ${{ env.FUNCTION_APP_NAME }}
          slot-name: staging
          package: ${{ env.BUNDLE_NAME }}.zip

      - name: Ping Staging Health
        if: ${{ env.USE_STAGING_SLOT == 'true' }}
        run: |
          curl \
            --retry 5 \
            --retry-max-time 120 \
            --retry-all-errors \
            -f 'https://${{ env.FUNCTION_APP_NAME }}-staging.azurewebsites.net${{ env.HEALTH_CHECK_PATH }}'

      - name: Swap Staging and Production Slots
        if: ${{ env.USE_STAGING_SLOT == 'true' }}
        run: |
          az webapp deployment slot swap \
            -g ${{ env.RESOURCE_GROUP_NAME }} \
            -n ${{ env.FUNCTION_APP_NAME }} \
            --slot staging \
            --target-slot production
