on:
  workflow_call:
    outputs:
      modules:
        value: ${{ jobs.get-all-modules.outputs.modules }}
        description: "List of all modules in the format [\"name1\", \"name2\"]"

jobs:
  get-all-modules:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Get all modules
        id: get-all-modules
        run: |
          folders_list=$(find infra/modules -mindepth 1 -maxdepth 1 -type d | sed 's#infra/modules/##' | jq -R -c . | jq -s -c .)
          echo "All modules: $folders_list"
          echo "modules=$folders_list" >> $GITHUB_OUTPUT
    outputs:
      modules: ${{ steps.get-all-modules.outputs.modules }}
