on:
  workflow_call:
    outputs:
      modules:
        value: ${{ jobs.get-modified-modules.outputs.modules }}
        description: "List of modified modules in the format [\"name1\", \"name2\"]"

jobs:
  get-modified-modules:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Get modified modules
        id: get-modules
        run: |
          folders_list=$(git diff --name-only ${{ github.event.pull_request.base.ref }} ${{ github.event.pull_request.head.ref }} infra/modules | xargs -r dirname | sed 's#^infra\/modules/\([^/]*\).*#\1#' | uniq | jq -R -c . | jq -s -c .)
          echo Modules changed: $folders_list
          echo "modules=$folders_list" >> $GITHUB_OUTPUT

    outputs:
      modules: ${{ steps.get-modules.outputs.modules }}
