on:
  workflow_call:
    inputs:
      base_branch:
        description: The branch to compare against the current branch. Defaults to "main".
        type: string
        required: false
        default: main

jobs:
  get-files-diff:
    name: Found GitHub files diff
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      actions: read

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        name: Checkout

      - name: Get changed files
        uses: ./.github/actions/github_modified_files
        id: modified_files
        with:
          base_branch: ${{ env.BASE_BRANCH }}
        env:
          BASE_BRANCH: ${{ inputs.base_branch }}