on:
  workflow_call:
    inputs:
      base_branch:
        description: The base branch
        type: string
        required: false
        default: main

concurrency:
  group: ${{ github.workflow }}-cd
  cancel-in-progress: true

jobs:
  get-files-diff:
    name: Found GitHub files diff
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      actions: read

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        name: Checkout
        with:
          fetch-depth: 0 # Recupera tutta la cronologia dei commit per assicurarsi che 'main' sia disponibile
  
      # - name: Fetch ${{ inputs.base_branch }} branch
      #   run: |
      #     git fetch origin ${{ inputs.base_branch }}

      - name: Get modified files
        id: modified_files
        run: |
          # Last base branch commit
          MAIN_COMMIT=$(git rev-parse origin/${{ inputs.base_branch }})
          echo "main_commit=$MAIN_COMMIT"

          # Last commit
          CURRENT_COMMIT=$(git rev-parse HEAD)
          echo "current_commit=$CURRENT_COMMIT"

          echo "$MODIFIED_FILES" | while read -r file; do
            if [[ -f "$file" ]]; then
              echo "$file"
            fi
          done > modified_files.txt

          MODIFIED_FILES=$(cat modified_files.txt)

          echo "Modified files:"
          echo $MODIFIED_FILES

          # Set output
          echo "files=$MODIFIED_FILES" >> $GITHUB_OUTPUT

    outputs:
      modules: ${{ steps.modified_files.outputs.files }}