name: Test Terraform modules plan

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - feats/make-modular-workflows-with-actions # FOR TESTING
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
    paths:
      - "infra/modules/**"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

env:
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_USE_OIDC: true
  ARM_USE_AZUREAD: true
  ARM_STORAGE_USE_AZUREAD: true

jobs:
  detect-modules:
    runs-on: ubuntu-latest
    name: Detect Modules to Test
    outputs:
      modules: ${{ steps.get-all-modules.outputs.modules || steps.get-modified-modules.outputs.modules }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Get all modules
        id: get-all-modules
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: ./.github/actions/get-all-modules

      - name: Get modified modules
        id: get-modified-modules
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: ./.github/actions/get-modified-modules

  terraform-test:
    runs-on: ubuntu-latest
    needs: detect-modules
    environment: dev-ci
    permissions:
      id-token: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        module: ${{ fromJSON(needs.detect-modules.outputs.modules) }}
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: ./.github/actions/azure-login
        name: Azure Login

      - name: Terraform Setup and init
        id: set-terraform-version
        uses: ./.github/actions/terraform-setup
        with:
          working_dir: infra/modules/${{ matrix.module }}

      - name: Terraform Test
        working-directory: infra/modules/${{ matrix.module }}
        run: |
          set -euo

          terraform test
