name: "Code Review"

on:
  workflow_call: {}

permissions:
  pull-requests: write

jobs:
  js_code_review:
    runs-on: ubuntu-latest

    env:
      TURBO_CACHE_DIR: .turbo-cache

    steps:
      - name: Check out code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Node Setup
        id: node-setup
        uses: pagopa/dx/.github/actions/node-setup@main

      - name: Post Plan on PR
        id: comment
        if: steps.node-setup.outputs.package-manager != 'pnpm' && github.event_name == 'pull_request'
        uses: pagopa/dx/actions/pr-comment@main
        with:
          comment-body: |
            ### ⚠️ Deprecation Notice
            Starting **January 16th, 2026**, the DX workflows will no longer support npm and yarn. All new builds will be required to use [**pnpm**](https://pnpm.io).

            > [!TIP]
            > Ready to make the switch? To help with the transition, we've published a **migration guide** on our blog, [check out the announcement for more details](https://dx.pagopa.it/blog/migrating-to-pnpm/).
          search-pattern: "Deprecation Notice"

      - name: Install dependencies (Yarn)
        if: ${{ steps.node-setup.outputs.package-manager == 'yarn' }}
        run: yarn install --immutable

      - name: Install dependencies (pnpm)
        if: ${{ steps.node-setup.outputs.package-manager == 'pnpm' }}
        run: pnpm install

      - name: Install dependencies (npm)
        if: ${{ steps.node-setup.outputs.package-manager == 'npm' }}
        run: npm ci

      # The code-review script must be defined in the root workspace
      # Example: "turbo run typecheck format:check lint:check test:coverage"
      # See https://github.com/pagopa/io-fims/pull/41
      - name: Run code-review script
        if: steps.node-setup.outputs.package-manager != ''
        run: ${{ steps.node-setup.outputs.package-manager }} run code-review

      # Codecov provides reports and metrics about test coverage data.
      # To enable set CODECOV_TOKEN secret at repo level
      - name: Upload coverage report to codecov.io
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        if: ${{ env.CODECOV_TOKEN != '' }}
        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5.5.1
        with:
          token: ${{ env.CODECOV_TOKEN }}
          codecov_yml_path: codecov.yml
