name: Keep Alive

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Run at 00:00 every day
  push:
    branches:
      - CES-12-keepalive

jobs:
  keep_alive:
    runs-on: 'ubuntu-20.04'
    permissions:
      contents: read
      actions: write

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.7

      - name: Calculate days since last commit
        id: commit_date
        run: |
          LAST_COMMIT_DATE=$(git log -1 --format=%ct)
          echo "Last commit date: $LAST_COMMIT_DATE"

          CURRENT_DATE=$(date +%s)
          echo "Current date: $CURRENT_DATE"

          DIFFERENCE=$(( ($CURRENT_DATE - $LAST_COMMIT_DATE) / 86400 ))
          echo "Days since last commit: $DIFFERENCE"

          echo "days_since_commit=$DIFFERENCE" >> $GITHUB_ENV

      - name: Keep Alive
        if: steps.commit_date.outputs.days_since_commit == '0'
        uses: ./.github/actions/keep-alive