name: Code Review - Legacy

# This workflow is used by functions that do not use the monorepo
# and still use a legacy architecture that will be deprecated in the future.

on:
  workflow_call:

jobs:
  js_code_review:
    runs-on: ubuntu-latest

    steps:
      - name: Check-out code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      # Corepack is an official tool by Node.js that manages package managers versions

      # This is needed to avoid
      # Error: Error when performing the request to https://registry.npmjs.org/yarn/latest;
      - name: Setup target Node.js to enable Corepack
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version-file: ".node-version"

      - name: Setup yarn
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version-file: ".node-version"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --immutable
        working-directory: .

      - name: Build
        run: yarn build

      - name: Lint
        run: yarn lint

      - name: Lint API
        run: yarn lint-api

      - name: Generate definitions
        run: yarn generate

      - name: Unit tests exec
        run: yarn test:coverage

      # Codecov provides reports and metrics about test coverage data.
      # To enable set CODECOV_TOKEN secret at repo level and make sure
      # that your "code-review" script creates a "coverage/" folder in
      # the root workspace.
      - name: Upload coverage report to codecov.io
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        if: ${{ env.CODECOV_TOKEN != '' }}
        uses: codecov/codecov-action@84508663e988701840491b86de86b666e8a86bed # v4.3.0
        with:
          token: ${{ env.CODECOV_TOKEN }}
