name: Code Review - Legacy

# This workflow is used by functions that do not use the monorepo
# and still use a legacy architecture that will be deprecated in the future.

on:
  workflow_call:

jobs:
  js_code_review:
    runs-on: ubuntu-latest

    steps:
      - name: Check-out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      # Corepack is an official tool by Node.js that manages package managers versions

      # This is needed to avoid
      # Error: Error when performing the request to https://registry.npmjs.org/yarn/latest;
      - name: Setup target Node.js to enable Corepack
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: ".node-version"

      - name: Setup yarn
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: ".node-version"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --immutable
        working-directory: .

      - name: Build
        run: yarn build

      - name: Lint
        run: yarn lint

      - name: Lint API
        run: yarn lint-api

      - name: Generate definitions
        run: yarn generate

      - name: Unit tests exec
        run: yarn test:coverage

      # Codecov provides reports and metrics about test coverage data.
      # To enable set CODECOV_TOKEN secret at repo level and make sure
      # that your "code-review" script creates a "coverage/" folder in
      # the root workspace.
      - name: Upload coverage report to codecov.io
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        if: ${{ env.CODECOV_TOKEN != '' }}
        uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4.6.0
        with:
          token: ${{ env.CODECOV_TOKEN }}
