name: OpenNext Release Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment for deployment"
        type: choice
        options:
          - dev
          - prod
        required: true
        default: dev
      workspace_name:
        description: "Name of the workspace to deploy"
        type: string
        required: true
        default: next-hello-world-app
      project_prefix:
        description: "Project name prefix for AWS resources (e.g., dx-d-eus1-devex)"
        type: string
        required: false
        default: dx-d-eus1-devex
      aws_region:
        description: "AWS region for deployment"
        type: choice
        options:
          - eu-south-1
          - us-east-1
          - eu-west-1
        required: false
        default: eu-south-1
      use_private_agent:
        description: "Use private agent for deployment"
        type: boolean
        required: false
        default: false

  push:
    branches:
      - main
    paths:
      - "apps/next-hello-world-app/**"
      - ".github/workflows/open_next_release.yaml"

jobs:
  deploy-opennext:
    name: Deploy Next.js App with OpenNext
    uses: pagopa/dx/.github/workflows/_release-bash-aws-open-next.yaml@opennext-module
    with:
      # Required inputs
      workspace_name: ${{ github.event.inputs.workspace_name || 'next-hello-world-app' }}
      environment: ${{ github.event.inputs.environment || 'dev' }}
      app_path: apps/next-hello-world-app

      # Optional inputs with defaults
      project_prefix: ${{ github.event.inputs.project_prefix || vars.PROJECT_PREFIX || 'dx-d-eus1-playground' }}
      aws_region: ${{ github.event.inputs.aws_region || 'eu-south-1' }}
      use_private_agent: ${{ github.event.inputs.use_private_agent == 'true' || false }}

    secrets: inherit
