name: Push modules to subrepo

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "infra/modules/**"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  get-modified-modules:
    uses: ./.github/workflows/get_modified_modules.yaml
    name: Get Modified Modules
    if: ${{ github.event_name != 'workflow_dispatch' }}
    # with:
    #   from_ref: ${{ github.event.before }}

  get-all-modules:
    uses: ./.github/workflows/get_all_modules.yaml
    name: Get All Modules
    if: ${{ github.event_name == 'workflow_dispatch' }}

  push-modified-modules:
    runs-on: ubuntu-latest
    needs: [get-modified-modules, get-all-modules]
    if: always()
    strategy:
      fail-fast: false
      matrix:
        module: ${{ fromJSON(needs.get-all-modules.outputs.modules || needs.get-modified-modules.outputs.modules) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
      - name: Push module to subrepository
        id: push-to-subrepository
        uses: ./.github/actions/push-module
        with:
          module: ${{ matrix.module }}
          github_pat: ${{ secrets.BOT_GH_TOKEN }}
