name: Push modules to subrepo

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "infra/modules/**"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  detect-modules:
    runs-on: ubuntu-latest
    name: Detect Modules to Test
    outputs:
      modules: ${{ steps.get-all-modules.outputs.modules || steps.get-modified-modules.outputs.modules }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Get all modules
        id: get-all-modules
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: ./.github/actions/get-all-modules

      - name: Get modified modules
        id: get-modified-modules
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: ./.github/actions/get-modified-modules

  push-modified-modules:
    runs-on: ubuntu-latest
    needs: [detect-modules]
    if: always()
    strategy:
      fail-fast: false
      matrix:
        module: ${{ fromJSON(needs.detect-modules.outputs.modules ) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
      - name: Push module to subrepository
        id: push-to-subrepository
        uses: ./.github/actions/push-module
        with:
          module: ${{ matrix.module }}
          github_pat: ${{ secrets.PUSH_TF_MODULES_PAT }}
