name: Push modules to subrepo

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "infra/modules/**"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  get-modified-modules:
    if: ${{ github.event_name != 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # Ensure we have enough history for the diff

      - name: Get modified modules
        id: get-modules
        run: |
          folders_list=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} infra/modules | xargs -r dirname | sed 's#^infra\/modules/\([^/]*\).*#\1#' | uniq | jq -R -c . | jq -s -c .)
          echo Modules that have changed: $folders_list
          echo "modules=$folders_list" >> $GITHUB_OUTPUT
    outputs:
      modules: ${{ steps.get-modules.outputs.modules }}

  get-all-modules:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get all modules
        id: get-all-modules
        run: |
          folders_list=$(find infra/modules -mindepth 1 -maxdepth 1 -type d | sed 's#infra/modules/##' | jq -R -c . | jq -s -c .)
          echo "All modules: $folders_list"
          echo "modules=$folders_list" >> $GITHUB_OUTPUT
    outputs:
      modules: ${{ steps.get-all-modules.outputs.modules }}

  push-modified-modules:
    runs-on: ubuntu-latest
    needs: [get-modified-modules, get-all-modules]
    strategy:
      matrix:
        module: ${{ fromJSON(needs.get-all-modules.outputs.modules || needs.get-modified-modules.outputs.modules) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push module to subrepository
        id: push-to-subrepository
        uses: ./.github/actions/push-module
        with:
          module: ${{ matrix.module }}
          github_pat: ${{ secrets.BOT_GH_TOKEN }}