name: Call Release Candidate Reusable Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  call_release_candidate:
    name: Call Release Candidate
    uses: pagopa/dx-playground/.github/workflows/release_candidate_command.yaml@main
    permissions:
      contents: write
      pull-requests: write
    concurrency: call-rc-${{ github.ref }}
    with:
      pr_number: ${{ github.event.pull_request.number }}
      distribution_type: beta
    secrets:
      gh_bot_pat: ${{ secrets.BOT_GH_TOKEN }}
      npm_token: ${{ secrets.NPM_TOKEN }}

#  call_snapshot:
#    name: Call Snapshot
#    uses: pagopa/dx-playground/.github/workflows/snapshot_command.yaml@main
#    permissions:
#      contents: write
#      pull-requests: write
#    concurrency: call-snapshot-${{ github.ref }}
#    with:
#      pr_number: ${{ github.event.pull_request.number }}
#      distribution_type: alpha
#    secrets:
#      gh_bot_pat: ${{ secrets.BOT_GH_TOKEN }}
#      npm_token: ${{ secrets.NPM_TOKEN }}
