name: Call Release Candidate Reusable Workflow
on:
  pull_request:
    types: [opened, synchronize, reopened]


jobs:
  call_release_candidate:
    name: Call Release Candidate
    concurrency: call-release-candidate-${{ github.ref }}
    uses: pagopa/dx-playground/.github/workflows/release_candidate_command.yaml@main
    secrets:
      gh_bot_pat: ${{ secrets.BOT_GH_TOKEN }}
      npm_token: ${{ secrets.NPM_TOKEN }}
    with:
      pr_number: ${{ github.event.pull_request.number }}

  call_snapshot:
    name: Call Snapshot
    concurrency: call-snapshot-${{ github.ref }}
    uses: pagopa/dx-playground/.github/workflows/snapshot_command.yaml@main
    secrets:
      gh_bot_pat: ${{ secrets.BOT_GH_TOKEN }}
      npm_token: ${{ secrets.NPM_TOKEN }}
    with:
      pr_number: ${{ github.event.pull_request.number }}
      distribution_type: alpha
