name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          # https://github.com/actions/checkout/issues/1471#issuecomment-1771231294
          fetch-tags: 'true'
          fetch-depth: 0

      - name: Node Setup and Install
        uses: ./.github/actions/node-setup-install

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@aba318e9165b45b7948c60273e0b72fce0a64eb9 # v1.4.7
        with:
          version: yarn run version
          publish: yarn run release
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
