name: Build and Deploy Static Site to Azure

# This reusable workflow builds a static application from a monorepo workspace,
# uploads the assets to an Azure Storage Account, and deploys them via Azure Front Door or Azure CDN Classic.
# It is designed to be called by other workflows.

on:
  workflow_call:
    inputs:
      workspace_name:
        description: The name of the workspace to create the artifact for.
        type: string
        required: true
      output_dir:
        description: The name of the build output directory.
        type: string
        required: false
        default: 'dist'
      storage_account_name:
        description: Azure Storage account name where the assets will be uploaded.
        type: string
        required: true
      blob_container_name:
        description: Blob container name within the Azure Storage account.
        type: string
        required: false
        default: '\$web'
      resource_group_name:
        description: CDN resource group name.
        type: string
        required: true
      profile_name:
        description: CDN Profile name associated with the endpoint.
        type: string
        required: true
      endpoint_name:
        description: CDN endpoint name where the assets will be served.
        type: string
        required: true
      environment:
        description: Environment where the artifact will be deployed.
        type: string
        required: true
      use_private_agent:
        description: Use a private agent to deploy the built artifact.
        type: boolean
        required: false
        default: false
      use_labels:
        description: Use labels to start the right environment's GitHub runner. If use_labels is true, also use_private_agent must be set to true
        type: boolean
        required: false
        default: false
      override_labels:
        description: Needed for special cases where the environment alone is not sufficient as a distinguishing label
        type: string
        required: false
        default: ''
      use_cdn_classic:
        description: Set to true to use Azure CDN Classic instead of Front Door (default is Front Door).
        type: boolean
        required: false
        default: false

concurrency:
  group: ${{ github.workflow }}-cd
  cancel-in-progress: true

env:
  BUNDLE_NAME: bundle
  OUTPUT_DIR: ${{ inputs.output_dir }}

jobs:
  build:
    name: Build Artifact
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Build Package
        id: build-package
        uses: pagopa/dx/.github/actions/build-workspace@main
        with:
          workspace_name: ${{ env.WORKSPACE_NAME }}
        env:
          WORKSPACE_NAME: ${{ inputs.workspace_name }}

      - name: Get Artifact path
        id: get-artifact-path
        working-directory: ${{ steps.build-package.outputs.workspace-path }}
        run: |
          echo "::debug::Packaging for static deployment"
          echo "artifact-path=$(realpath ./$OUTPUT_DIR)" >> $GITHUB_OUTPUT
        env:
          OUTPUT_DIR: ${{ env.OUTPUT_DIR }}

      - name: Upload Artifact
        uses: pagopa/dx/.github/actions/upload-artifact@main
        with:
          bundle_name: ${{ env.BUNDLE_NAME }}
          file_path: ${{ steps.get-artifact-path.outputs.artifact-path }}

  deploy:
    name: Deploy
    runs-on: ${{ inputs.use_labels && inputs.use_private_agent && (inputs.override_labels != '' && inputs.override_labels || inputs.environment) || inputs.use_private_agent && 'self-hosted' || 'ubuntu-latest' }}
    needs: [build]
    if: ${{ !github.event.act }}
    environment: ${{ inputs.environment }}-cd
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Download Artifact
        uses: pagopa/dx/.github/actions/download-artifact@main
        with:
          bundle_name: ${{ env.BUNDLE_NAME }}
          file_path: "./${{ env.OUTPUT_DIR }}"

      - name: Azure Login
        uses: pagopa/dx/.github/actions/azure-login@main
        env:
          ARM_USE_OIDC: true
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: Deploy Assets and Purge CDN
        uses: pagopa/dx/actions/static-assets-deploy@main
        with:
          use_cdn_classic: ${{ env.USE_CDN_CLASSIC }}
          storage_account_name: ${{ env.STORAGE_ACCOUNT_NAME }}
          blob_container_name: "${{ env.BLOB_CONTAINER_NAME }}"
          resource_group_name: ${{ env.RESOURCE_GROUP_NAME }}
          profile_name: ${{ env.CDN_PROFILE_NAME }}
          endpoint_name: ${{ env.CDN_ENDPOINT_NAME }}
          sync_dir_name: ${{ env.OUTPUT_DIR }}
        env:
          STORAGE_ACCOUNT_NAME: ${{ inputs.storage_account_name }}
          RESOURCE_GROUP_NAME: ${{ inputs.resource_group_name }}
          CDN_PROFILE_NAME: ${{ inputs.profile_name }}
          CDN_ENDPOINT_NAME: ${{ inputs.endpoint_name }}
          BLOB_CONTAINER_NAME: ${{ inputs.blob_container_name }}
          USE_CDN_CLASSIC: ${{ inputs.use_cdn_classic && 'true' || 'false' }}
