name: Terraform Validation

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    paths:
      - infra/**
      - .terraform-version
      - .pre-commit-config.yaml
      - .trivyignore

jobs:
  tf_analysis:
    uses: ./.github/workflows/static_analysis.yaml
    name: Terraform Validation
    secrets: inherit
    with:
      terraform_version: "1.7.5"
      pre_commit_tf_tag: "v1.94.1@sha256:638e8892cb2647240c175064254c2fda80214597275c81a360a878dc80323076"
      enable_modified_files_detection: true
      enable_terraform_test: true