name: Terraform Validation

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    paths:
      - infra/**
      - .terraform-version
      - .pre-commit-config.yaml
      - .trivyignore

jobs:
  get-terraform-version:
    uses: ./.github/workflows/get_terraform_version.yaml
    name: Get terraform version from .terraform-version file

  tf_analysis:
    uses: ./.github/workflows/static_analysis.yaml
    needs: [ get-terraform-version ]
    name: Terraform Validation
    secrets: inherit
    with:
      terraform_version: needs.get-terraform-version.outputs.terraform_version
      pre_commit_tf_tag: "v1.96.2@sha256:01f870b7689b5a09c1a370914fcddcac42c4b6478c9d369e1d2590dd0a66ffd0"
      enable_modified_files_detection: true
