name: Diff Test

on:
  workflow_dispatch:
    inputs:
      content_paths:
        description: If you want to include only specific file set True else False
        type: boolean
        required: false
        default: false
  push:
    branches:
      - DEVEX-165-cdn-action-template

# jobs:
#   drift_detection:
#     uses: ./.github/workflows/github_modified_files.yaml
#     name: DIFF TEST
#     secrets: inherit

jobs:
  test:
    name: TEST
    runs-on: ubuntu-22-04
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Found modified files
        if: ${{ inputs.content_paths }}
        uses: ./.github/workflows/github_modified_files.yaml
        id: modified_files

      - name: Purge CDN Specific Paths
        if: ${{ inputs.content_paths && steps.modified_files.outputs.files != '' }}
        run: |
          echo -e "${{ steps.modified_files.outputs.files }}" | awk '{printf " '\''%s'\''", $0}'

      - name: Purge CDN
        if: ${{ !inputs.content_paths || steps.modified_files.outputs.files == '' }}
        run: |
          echo "/*"