name: Diff Test

on:
  workflow_dispatch:
    inputs:
      content_paths:
        description: If you want to include only specific file set 'true' else 'false'
        type: string
        required: false
  push:
    branches:
      - DEVEX-165-cdn-action-template

# jobs:
#   drift_detection:
#     uses: ./.github/workflows/github_modified_files.yaml
#     name: DIFF TEST
#     secrets: inherit

env:
  CONTENT_PATH: ${{ inputs.content_paths == '' && 'true' || 'false' }}

jobs:
  test:
    name: TEST
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      actions: read

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        name: Checkout

      - run: echo '${{ env.CONTENT_PATH }}'

      - name: Found modified files
        if: ${{ env.CONTENT_PATH == 'true' }}
        uses: ./.github/actions/github_modified_files
        id: modified_files
        with:
          base_branch: main

      - name: Purge CDN Specific Paths
        if: ${{ env.CONTENT_PATH == 'true' && steps.modified_files.outputs.modified_files != '' }}
        run: |
          echo -e "${{ steps.modified_files.outputs.modified_files }}" | awk '{printf " '\''%s'\''", $0}'

      - name: Purge CDN
        if: ${{ env.CONTENT_PATH == 'false' || steps.modified_files.outputs.modified_files == '' }}
        run: |
          echo "/*"