name: Validate

on:
  workflow_call:

jobs:
  warn-missing-version-plans:
    name: Warn Missing Version Plans
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      pull-requests: write
    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Setup Node.js
        uses: pagopa/dx/.github/actions/node-setup@main

      - name: Install dependencies
        run: pnpm install

      - name: Warn missing version plan coverage
        uses: pagopa/dx/actions/nx-release@main
        with:
          github-token: ${{ github.token }}

  ci:
    name: Code Review
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      pull-requests: read
    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Setup Node.js
        uses: pagopa/dx/.github/actions/node-setup@main

      - name: Setup Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version-file: "go.work"
          cache-dependency-path: "providers/**/*.sum"

      - name: Setup Terraform
        uses: pagopa/dx/.github/actions/terraform-setup@main

      - name: Install dependencies
        run: pnpm install

      - name: Cache Nx
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: .nx
          key: ${{ runner.os }}-nx-cache-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-nx-cache-

      - name: Sets the base and head SHAs required for `nx affected` command
        uses: nrwl/nx-set-shas@3e9ad7370203c1e93d109be57f3b72eb0eb511b1

      - name: Run code quality checks on affected projects
        run: pnpm validate
